-- Original, deterministic demonstration content. This is an authored starting
-- bank, not expert-reviewed or empirically calibrated assessment material.
-- No existing course, question, learner, attempt, or mastery row is changed.
-- The migration runner wraps this file in one transaction; 0031 validates
-- option cardinality at commit after questions and options have both arrived.

INSERT INTO domains (id, slug, name, description, icon, sort_order)
VALUES (md5('learnpath:quant:domain')::uuid, 'quantitative-reasoning', 'Quantitative Reasoning',
  'Interpret quantities, comparisons, and small data sets in everyday situations.', 'BarChart3', 20);

INSERT INTO courses (id, domain_id, slug, name, description, level, estimated_hours)
VALUES (md5('learnpath:quant:course')::uuid, md5('learnpath:quant:domain')::uuid,
  'everyday-quantitative-reasoning', 'Everyday Quantitative Reasoning',
  'Reason about unit prices, percentages, tables, and numerical summaries. Short assessment sessions build a visible skill-by-skill evidence record. Original demonstration content; expert review and learner calibration are still required.',
  'BEGINNER', 6.0);

INSERT INTO modules (id, course_id, slug, name, description, sequence)
SELECT md5('learnpath:quant:module:' || item.slug)::uuid, md5('learnpath:quant:course')::uuid,
  item.slug, item.name, item.description, item.sequence
FROM (VALUES
  ('proportions-percentages', 'Proportions and Percentages', 'Compare rates and find percentage amounts using a clearly identified whole.', 1),
  ('reading-comparisons', 'Reading Data and Change', 'Read table labels accurately and distinguish percentage change from percentage-point change.', 2),
  ('summarizing-data', 'Summarizing Small Data Sets', 'Calculate and interpret the mean, median, and range without hiding the effect of unusual values.', 3)
) AS item(slug, name, description, sequence);

CREATE TEMP TABLE quant_skills ON COMMIT DROP AS
SELECT * FROM jsonb_to_recordset($quant_skills$
[
  {
    "slug":"unit-rates","name":"Unit Rates and Proportional Scaling","module":"proportions-percentages","sequence":1,"difficulty":2,
    "description":"Calculate a quantity per one unit, compare like-for-like unit prices, and scale quantities only when a constant-rate assumption is justified.",
    "lessons":[
      {"type":"CONCEPT_GUIDE","title":"Compare quantities per one unit","summary":"Use units and constant-rate assumptions to make fair comparisons.","objectives":["Calculate a unit rate with its units.","Scale a proportional relationship by multiplication.","Identify a fixed fee that breaks proportional scaling."],"sections":[
        {"heading":"Make the denominator one","body":"A rate compares two quantities with different units. If 6 notebooks cost 90 currency units, divide both quantities by 6: the unit price is 15 currency units per notebook. Write the units beside the calculation. Reversing the division gives notebooks per currency unit, a different rate with a different interpretation."},
        {"heading":"Scale both quantities together","body":"At a constant price of 15 per notebook, 4 notebooks cost 4 times 15 = 60. The relationship is proportional because doubling the quantity doubles the cost and zero notebooks cost zero. This assumption must come from the situation; a membership fee, delivery charge, or bulk discount can break it."},
        {"heading":"Compare the same units","body":"A 750 g pack costing 90 has a price of 120 per kilogram. A 1 kg pack costing 125 is more expensive per kilogram despite its larger size. Convert to common units before comparing. The lower unit price does not automatically make a purchase suitable: the amount needed and possible waste also matter."}
      ]},
      {"type":"WORKED_EXAMPLE","title":"Choose between two rice packs","summary":"Convert package sizes to a shared unit and check a quantity estimate.","objectives":["Convert grams to kilograms for a unit-price comparison.","Calculate a cost for a new quantity.","Check when a proportional estimate is justified."],"sections":[
        {"heading":"1. Put the packs on one scale","body":"Pack A contains 2 kg and costs 150. Pack B contains 750 g and costs 60. Convert 750 g to 0.75 kg. The unit prices are 150 / 2 = 75 per kg and 60 / 0.75 = 80 per kg."},
        {"heading":"2. Interpret the comparison","body":"Pack A costs 5 less per kilogram. This is a comparison of rates, not just sticker prices: Pack B has the lower total price but supplies much less rice."},
        {"heading":"3. State the assumption","body":"At Pack A's constant rate, 3 kg would cost 3 times 75 = 225. That estimate is valid only if the same rate is offered for 3 kg and there is no added fee. If only whole packs can be bought, a shopper cannot necessarily purchase exactly 3 kg at that rate."}
      ]}
    ]
  },
  {
    "slug":"percentage-amounts","name":"Percentages of a Whole","module":"proportions-percentages","sequence":2,"difficulty":2,
    "description":"Identify the relevant whole, convert a percentage to a fraction or decimal, and calculate a part or a whole in everyday contexts.",
    "lessons":[
      {"type":"CONCEPT_GUIDE","title":"Find the whole before using a percentage","summary":"Connect percentages, decimals, parts, and totals.","objectives":["Interpret a percentage as a number per hundred.","Calculate a percentage of a specified whole.","Recover a whole from a known part and percentage."],"sections":[
        {"heading":"Percent means per hundred","body":"35% means 35 out of every 100 equal parts of the relevant whole. As a decimal it is 0.35, and as a fraction it is 35/100. A percentage needs a base: 35% of 20 and 35% of 200 are different amounts."},
        {"heading":"Move from a whole to a part","body":"To find 35% of 200, multiply 0.35 by 200 to get 70. An estimate can catch errors: 35% is less than half, so the part must be less than 100. For a discount, this calculation gives the amount removed; subtract it from the original price to find the amount paid."},
        {"heading":"Move from a part to a whole","body":"If 70 learners represent 35% of a group, the total is 70 / 0.35 = 200. Check by multiplying the total by 0.35. Adding 35 to 70 or dividing 70 by 35 without accounting for percent does not recover the whole."}
      ]},
      {"type":"WORKED_EXAMPLE","title":"Separate a discount from the price paid","summary":"Calculate a percentage amount and verify the result.","objectives":["Calculate a discount amount.","Calculate the remaining price.","Recover an original price from a discounted price."],"sections":[
        {"heading":"1. Identify the original whole","body":"A jacket originally costs 800 and has a 15% discount. The whole for the discount is 800. The discount amount is 0.15 times 800 = 120."},
        {"heading":"2. Find what remains","body":"The customer pays 800 - 120 = 680. Equivalently, the customer pays 85% of the original price: 0.85 times 800 = 680. A discount of 15% does not mean a discount of 15 currency units."},
        {"heading":"3. Work backward","body":"If only the sale price 680 and the 15% discount were given, write 0.85 times original price = 680. Divide by 0.85 to recover 800. Taking 15% of 680 and adding it back uses the wrong whole."}
      ]}
    ]
  },
  {
    "slug":"reading-data-tables","name":"Reading Data Tables","module":"reading-comparisons","sequence":1,"difficulty":2,
    "description":"Read a labeled cell, combine non-overlapping categories, and distinguish a subgroup value from a row, column, or grand total.",
    "lessons":[
      {"type":"CONCEPT_GUIDE","title":"Read the labels before the numbers","summary":"Use row labels, column labels, units, and totals to interpret a table.","objectives":["Locate a cell using both row and column labels.","Add non-overlapping table categories correctly.","Recognize information that the table does not provide."],"sections":[
        {"heading":"A cell has two labels","body":"Suppose a library table lists Monday and Tuesday as rows, with adult and child visits as columns. The Monday-child cell counts child visits on Monday. It is neither all Monday visits nor all child visits. Read the title and units too: visits are not necessarily distinct visitors."},
        {"heading":"Totals depend on the question","body":"With Monday values adult 18 and child 12, Monday's total is 30. If Tuesday has adult 22 and child 8, the adult column total is 40 and the grand total is 60. Add each contributing cell once. Adding row totals and column totals together would count every visit twice."},
        {"heading":"Respect what is missing","body":"A two-day visit table cannot establish the number of unique people unless repeated visits are identified. It also cannot establish the reason for a change. Arithmetic comparisons describe the recorded values; causal explanations require additional evidence."}
      ]},
      {"type":"WORKED_EXAMPLE","title":"Trace a small transport table","summary":"Answer distinct questions from the same four cells.","objectives":["Read a subgroup count.","Calculate row and column totals.","Avoid inferring individual behavior from aggregate counts."],"sections":[
        {"heading":"1. Read the table","body":"A survey records one usual transport choice per learner. Group A: bus 14, walk 6. Group B: bus 9, walk 11. The value 9 describes Group B learners who chose bus."},
        {"heading":"2. Choose the relevant cells","body":"Group A contains 14 + 6 = 20 learners. Across both groups, 6 + 11 = 17 learners chose walking. The survey total is 14 + 6 + 9 + 11 = 40, so 23 chose bus and 17 chose walking."},
        {"heading":"3. State the limit","body":"The table shows more bus choices in Group A than Group B. It does not show that moving a learner to Group A changes that learner's transport choice. Group membership and transport choice are recorded categories, not an experiment."}
      ]}
    ]
  },
  {
    "slug":"percentage-change","name":"Percentage Change and Percentage Points","module":"reading-comparisons","sequence":2,"difficulty":3,
    "description":"Calculate relative change using the original value, distinguish percentage points from percentage change, and compose successive percentage changes.",
    "lessons":[
      {"type":"CONCEPT_GUIDE","title":"Measure change against its starting value","summary":"Keep absolute differences, relative changes, and percentage points distinct.","objectives":["Calculate a percentage increase or decrease from an original value.","Distinguish percentage points from relative percentage change.","Use successive multipliers for successive changes."],"sections":[
        {"heading":"The original value is the base","body":"When a quantity rises from 80 to 100, the difference is 20. Relative to the original 80, the increase is 20 / 80 = 0.25 = 25%. Dividing by the final 100 answers a different question. For a decrease, divide the amount lost by the original value and describe the direction explicitly."},
        {"heading":"Percentages can themselves change","body":"If a survey share rises from 20% to 30%, it rises by 10 percentage points. Its relative increase is (30 - 20) / 20 = 50%. Both statements are correct because they measure different things. State which measure is requested."},
        {"heading":"Successive changes use new bases","body":"Increasing a price by 10% multiplies it by 1.10. Decreasing that new price by 10% multiplies by 0.90. The combined multiplier is 0.99, giving a net 1% decrease. Equal percentage changes in opposite directions do not generally cancel because their bases differ."}
      ]},
      {"type":"WORKED_EXAMPLE","title":"Explain a rise and a reversal","summary":"Follow the original base at each step of a changing quantity.","objectives":["Calculate a relative increase.","Calculate the different percentage needed to reverse that increase.","Check the answer using a multiplier."],"sections":[
        {"heading":"1. Find the first change","body":"A club grows from 40 members to 50. It gains 10 members, so its percentage increase is 10 / 40 times 100 = 25%. The growth multiplier is 1.25."},
        {"heading":"2. Reverse from the new base","body":"Returning from 50 members to 40 means losing 10 out of the current 50. That is a 20% decrease, not 25%. The decrease multiplier is 0.80."},
        {"heading":"3. Verify both steps","body":"40 times 1.25 = 50 and 50 times 0.80 = 40. The multipliers 1.25 and 0.80 multiply to 1, which verifies the reversal. Always name the starting quantity for the step being measured."}
      ]}
    ]
  },
  {
    "slug":"arithmetic-mean","name":"Arithmetic Mean","module":"summarizing-data","sequence":1,"difficulty":2,
    "description":"Calculate a mean from a sum and count, recover a missing value, and combine groups using their sizes rather than averaging their means blindly.",
    "lessons":[
      {"type":"CONCEPT_GUIDE","title":"Treat the mean as a shared total","summary":"Connect a mean to the sum and number of observations.","objectives":["Calculate the arithmetic mean from a sum and count.","Recover a total from a mean and count.","Combine unequal groups using their totals."],"sections":[
        {"heading":"Share the total equally","body":"The arithmetic mean of 4, 7, and 10 is (4 + 7 + 10) / 3 = 7. It is the value each observation would have if the same total were shared equally. Include every observation, including repeated values and zeros, in both the appropriate sum and the count."},
        {"heading":"Reverse the relationship","body":"Mean times count equals total. If 5 daily counts have mean 12, their total is 60. If four known days sum to 49, the remaining day must be 11. This is often clearer than guessing a missing value from the other numbers."},
        {"heading":"Combine groups with their sizes","body":"Two groups of different sizes do not contribute equally to a combined mean. If 2 readings average 10 and 6 readings average 14, their totals are 20 and 84. The combined mean is 104 / 8 = 13, not the unweighted average 12. A very large observation can also pull the mean upward."}
      ]},
      {"type":"WORKED_EXAMPLE","title":"Combine reading-time summaries","summary":"Use group counts to reconstruct a correct overall mean.","objectives":["Recover group totals from means.","Calculate an overall mean for unequal groups.","Explain why a mean need not be an observed value."],"sections":[
        {"heading":"1. Recover the totals","body":"Three learners read for an average of 20 minutes, giving a total of 60 learner-minutes. Two other learners average 35 minutes, giving a total of 70 learner-minutes."},
        {"heading":"2. Combine total and count","body":"The five learners have a combined total of 130 minutes. Their overall mean is 130 / 5 = 26 minutes. Averaging 20 and 35 would give 27.5, which would wrongly give the two groups equal weight."},
        {"heading":"3. Interpret the result","body":"The mean 26 describes a shared-total summary; it does not claim that anyone read for exactly 26 minutes. It lies between the two group means and is closer to 20 because more learners belong to that group."}
      ]}
    ]
  },
  {
    "slug":"median-and-range","name":"Median and Range","module":"summarizing-data","sequence":2,"difficulty":2,
    "description":"Order observations to find a median, calculate the range, and explain how an extreme value can alter spread without changing the median.",
    "lessons":[
      {"type":"CONCEPT_GUIDE","title":"Separate the center from the spread","summary":"Find the median and range by sorting and checking endpoints.","objectives":["Find the median of odd and even numbers of observations.","Calculate the range from the maximum and minimum.","Explain the effect of an extreme value on median and range."],"sections":[
        {"heading":"Sort before locating the middle","body":"The median is the middle value after arranging observations in order. For 9, 2, 5, 5, 12, the sorted list is 2, 5, 5, 9, 12 and the median is 5. Keep repeated values: each is a separate observation. Choosing the middle position in an unsorted list can give the wrong result."},
        {"heading":"Handle an even count","body":"For 2, 4, 8, 10, there are two middle observations, 4 and 8. The median is their average, 6. The median does not have to appear in the data. It is not generally the average of the smallest and largest values."},
        {"heading":"Measure spread with the endpoints","body":"The range is maximum minus minimum. For 2, 5, 5, 9, 12 the range is 10. If 12 becomes 100, the median stays 5 but the range grows to 98. Range describes the distance between endpoints, not how all intermediate values are distributed."}
      ]},
      {"type":"WORKED_EXAMPLE","title":"Inspect a late delivery","summary":"See how a single unusual observation changes different summaries.","objectives":["Sort a small list without removing duplicates.","Find its median and range.","Recalculate after one endpoint changes."],"sections":[
        {"heading":"1. Sort the delivery times","body":"Five delivery times in minutes are 18, 12, 15, 12, 23. Sorting gives 12, 12, 15, 18, 23. The third observation is the median, 15 minutes."},
        {"heading":"2. Calculate the range","body":"The longest delivery is 23 minutes and the shortest is 12 minutes. The range is 23 - 12 = 11 minutes. It has the same units as the observations."},
        {"heading":"3. Change the unusual delivery","body":"If the final delivery took 50 minutes instead of 23, the sorted list would be 12, 12, 15, 18, 50. The middle observation would still be 15, but the range would become 50 - 12 = 38 minutes. These summaries describe different features of the same data."}
      ]}
    ]
  }
]
$quant_skills$::jsonb) AS content(slug text, name text, module text, sequence integer, difficulty integer, description text, lessons jsonb);

INSERT INTO skills (id, domain_id, slug, name, description, category, difficulty, estimated_minutes)
SELECT md5('learnpath:quant:skill:' || slug)::uuid, md5('learnpath:quant:domain')::uuid,
  slug, name, description, 'QUANTITATIVE_REASONING', difficulty, 45 FROM quant_skills;

INSERT INTO course_skills (course_id, module_id, skill_id, sequence, is_required)
SELECT md5('learnpath:quant:course')::uuid, md5('learnpath:quant:module:' || module)::uuid,
  md5('learnpath:quant:skill:' || slug)::uuid, sequence, TRUE FROM quant_skills;

-- Relative percentage change requires identifying a percentage base. Table
-- reading, mean, median/range, and unit rates remain independent entry points.
INSERT INTO skill_prerequisites (skill_id, prerequisite_skill_id, required_mastery, relationship_type)
VALUES (md5('learnpath:quant:skill:percentage-change')::uuid,
  md5('learnpath:quant:skill:percentage-amounts')::uuid, 0.65, 'REQUIRED');

CREATE TEMP TABLE quant_questions ON COMMIT DROP AS
SELECT * FROM jsonb_to_recordset($quant_questions$
[
  {"slug":"rates-d1","skill":"unit-rates","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"REMEMBER","difficulty":1,"prompt":"A unit price tells you which quantity?","explanation":"A unit price gives cost for one specified unit, such as currency units per kilogram. Total cost and package size are needed to calculate it but are not themselves the unit price.","options":[{"content":"The total cost of all packages","correct":false,"code":"TOTAL_AS_UNIT_RATE"},{"content":"The cost for one unit of quantity","correct":true},{"content":"The number of units in the largest package","correct":false,"code":"QUANTITY_AS_UNIT_RATE"},{"content":"The difference between two package prices","correct":false,"code":"DIFFERENCE_AS_RATE"}]},
  {"slug":"rates-d2","skill":"unit-rates","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":4,"prompt":"A taxi charges a fixed 40 plus 12 per kilometre. A 5 km ride costs 100. What is the cost of a 10 km ride?","explanation":"The fixed 40 is paid once. A 10 km ride costs 40 + 12 times 10 = 160. Doubling the 5 km total would count the fixed charge twice.","options":[{"content":"200","correct":false,"code":"FIXED_FEE_SCALED"},{"content":"120","correct":false,"code":"FIXED_FEE_OMITTED"},{"content":"160","correct":true},{"content":"140","correct":false,"code":"DISTANCE_CHARGE_UNCHANGED"}]},
  {"slug":"rates-d3","skill":"unit-rates","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"UNDERSTAND","difficulty":2,"prompt":"Four kilograms of apples cost 120 at a constant price, with no fees or discounts. Select every correct statement.","explanation":"The unit price is 120 / 4 = 30 per kg. Multiplying this rate gives 60 for 2 kg and 180 for 6 kg. Dividing quantity by cost would instead give kg per currency unit.","options":[{"content":"The unit price is 30 per kg.","correct":true},{"content":"Two kilograms cost 60.","correct":true},{"content":"Six kilograms cost 720.","correct":false,"code":"TOTAL_PRICE_AS_UNIT_RATE"},{"content":"The unit price is 4/120 currency units per kg.","correct":false,"code":"INVERTED_RATE"}]},
  {"slug":"rates-d4","skill":"unit-rates","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Pack A holds 500 g of rice for 45. Pack B holds 750 g for 60. There are no added charges. Select every comparison justified by these figures.","explanation":"Pack A costs 45 / 0.5 = 90 per kg; Pack B costs 60 / 0.75 = 80 per kg. B has the lower unit price, while A has the lower total pack price. Package size alone does not establish unit-price value.","options":[{"content":"Pack A costs 90 per kg.","correct":true},{"content":"Pack A has the lower unit price because its pack price is lower.","correct":false,"code":"STICKER_PRICE_COMPARISON"},{"content":"Pack B costs 80 per kg.","correct":true},{"content":"Both packs have the same unit price because both prices are below 100.","correct":false,"code":"COMMON_BOUND_AS_EQUAL_RATE"}]},
  {"slug":"rates-d5","skill":"unit-rates","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":2,"prompt":"Six identical notebooks cost 90 in total. What is the price of one notebook? Enter the number of currency units.","explanation":"Divide the total cost by the number of notebooks: 90 / 6 = 15 currency units per notebook.","answer":15,"tolerance":0,"unit":"currency units","options":[]},
  {"slug":"rates-d6","skill":"unit-rates","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":3,"prompt":"A recipe uses 180 g of flour for 4 servings. At the same amount per serving, how many grams are needed for 10 servings?","explanation":"Each serving uses 180 / 4 = 45 g. Ten servings need 45 times 10 = 450 g.","answer":450,"tolerance":0,"unit":"grams","options":[]},
  {"slug":"percent-d1","skill":"percentage-amounts","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"REMEMBER","difficulty":1,"prompt":"Which decimal is equal to 7%?","explanation":"Percent means per hundred. Seven percent is 7/100 = 0.07; 0.7 would mean 70%.","options":[{"content":"0.7","correct":false,"code":"PERCENT_DECIMAL_ONE_PLACE"},{"content":"7","correct":false,"code":"PERCENT_NOT_CONVERTED"},{"content":"0.007","correct":false,"code":"PERCENT_DECIMAL_THREE_PLACES"},{"content":"0.07","correct":true}]},
  {"slug":"percent-d2","skill":"percentage-amounts","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":4,"prompt":"A 20% discount leaves a sale price of 640. What was the original price?","explanation":"The sale price is 80% of the original price. Divide 640 by 0.80 to get 800. Adding 20% of the sale price uses the wrong base.","options":[{"content":"800","correct":true},{"content":"768","correct":false,"code":"REVERSE_DISCOUNT_WRONG_BASE"},{"content":"660","correct":false,"code":"PERCENT_AS_ABSOLUTE_AMOUNT"},{"content":"512","correct":false,"code":"DISCOUNT_APPLIED_AGAIN"}]},
  {"slug":"percent-d3","skill":"percentage-amounts","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"UNDERSTAND","difficulty":2,"prompt":"Select every expression equal to 25% of 80.","explanation":"25% is one quarter or 0.25. Both 80 / 4 and 0.25 times 80 equal 20. Dividing by 25 or multiplying by 25 does not convert the percentage correctly.","options":[{"content":"80 / 4","correct":true},{"content":"80 / 25","correct":false,"code":"PERCENT_AS_DIVISOR"},{"content":"0.25 times 80","correct":true},{"content":"25 times 80","correct":false,"code":"PERCENT_NOT_CONVERTED"}]},
  {"slug":"percent-d4","skill":"percentage-amounts","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"In a group of 40 people, 30% cycle to work. In a separate group of 60 people, 20% cycle to work. Select every correct statement.","explanation":"The cycling counts are 0.30 times 40 = 12 and 0.20 times 60 = 12. The equal counts do not imply equal percentages because the group sizes differ. Together, 24 of 100 people cycle, or 24%.","options":[{"content":"More people cycle in the first group because 30% is greater than 20%.","correct":false,"code":"PERCENT_WITHOUT_BASE"},{"content":"The same number of people cycle in each group.","correct":true},{"content":"Together, 50% cycle because 30% + 20% = 50%.","correct":false,"code":"ADDING_SUBGROUP_PERCENTAGES"},{"content":"Together, 24% of the 100 people cycle.","correct":true}]},
  {"slug":"percent-d5","skill":"percentage-amounts","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":2,"prompt":"What is 15% of 240? Enter the amount, not the percent sign.","explanation":"10% of 240 is 24 and 5% is 12. Adding gives 36; equivalently, 0.15 times 240 = 36.","answer":36,"tolerance":0,"unit":"units","options":[]},
  {"slug":"percent-d6","skill":"percentage-amounts","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":3,"prompt":"Eighteen learners are 30% of a class. How many learners are in the whole class?","explanation":"Write 0.30 times class size = 18. The class size is 18 / 0.30 = 60 learners.","answer":60,"tolerance":0,"unit":"learners","options":[]},
  {"slug":"tables-d1","skill":"reading-data-tables","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"UNDERSTAND","difficulty":1,"prompt":"A library table has rows Monday and Tuesday and columns Adult visits and Child visits. Monday: adult 18, child 12. Tuesday: adult 22, child 8. What does the value 8 describe?","explanation":"The value 8 is at the intersection of Tuesday and Child visits. It counts child visits on Tuesday, not all Tuesday visits or all visits by children.","options":[{"content":"All visits on Tuesday","correct":false,"code":"CELL_AS_ROW_TOTAL"},{"content":"Child visits on Tuesday","correct":true},{"content":"Child visits across both days","correct":false,"code":"CELL_AS_COLUMN_TOTAL"},{"content":"Adult visits on Monday","correct":false,"code":"ROW_COLUMN_SWAP"}]},
  {"slug":"tables-d2","skill":"reading-data-tables","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":4,"prompt":"A cafe records drinks sold. Morning: tea 24, coffee 18. Afternoon: tea 16, coffee 22. Which conclusion is supported by the table alone?","explanation":"Tea sales total 24 + 16 = 40. The table records drinks, so it cannot establish the number of distinct customers, their preferences, or why counts differ.","options":[{"content":"Exactly 80 different people bought drinks.","correct":false,"code":"EVENTS_AS_UNIQUE_PEOPLE"},{"content":"Every morning customer prefers tea.","correct":false,"code":"AGGREGATE_AS_INDIVIDUAL_CLAIM"},{"content":"The cafe sold 40 teas in total.","correct":true},{"content":"Afternoon weather caused more coffee sales.","correct":false,"code":"COUNTS_AS_CAUSATION"}]},
  {"slug":"tables-d3","skill":"reading-data-tables","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"UNDERSTAND","difficulty":2,"prompt":"Each learner chooses exactly one lunch. Group A: rice 9, noodles 6. Group B: rice 7, noodles 8. Select every correct total.","explanation":"Group A has 9 + 6 = 15 learners. Rice totals 9 + 7 = 16 and noodles total 6 + 8 = 14. The grand total is 30, counting each learner once.","options":[{"content":"Group A has 15 learners.","correct":true},{"content":"Across both groups, 16 learners chose rice.","correct":true},{"content":"Across both groups, 17 learners chose noodles.","correct":false,"code":"DIAGONAL_AS_COLUMN_TOTAL"},{"content":"There are 60 learners because row totals and column totals add to 60.","correct":false,"code":"DOUBLE_COUNTED_TOTALS"}]},
  {"slug":"tables-d4","skill":"reading-data-tables","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"A workshop records attendance by session: Monday, beginners 10 and experienced 14; Tuesday, beginners 16 and experienced 8. A person may attend both days. Select every supported statement.","explanation":"Each day has 24 attendances. Beginner attendances total 26. Because people may attend both days, 48 attendances do not establish 48 distinct people, and experienced attendances fell by 6 rather than rose.","options":[{"content":"Tuesday had more total attendances than Monday.","correct":false,"code":"ONE_CELL_AS_TOTAL_COMPARISON"},{"content":"Both days recorded 24 attendances.","correct":true},{"content":"There were exactly 48 distinct attendees.","correct":false,"code":"EVENTS_AS_UNIQUE_PEOPLE"},{"content":"Beginner attendances totaled 26 across both days.","correct":true}]},
  {"slug":"tables-d5","skill":"reading-data-tables","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":2,"prompt":"A shop table lists units sold: Monday, pens 14 and pencils 9; Tuesday, pens 11 and pencils 16. How many pencils were sold across both days?","explanation":"Use the pencil column only: 9 + 16 = 25 pencils.","answer":25,"tolerance":0,"unit":"pencils","options":[]},
  {"slug":"tables-d6","skill":"reading-data-tables","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"ANALYZE","difficulty":3,"prompt":"A survey table has mutually exclusive Bus and Walk columns. Group A has 13 Bus, 7 Walk, total 20. Group B has 9 Bus, an unknown Walk count, total 24. What is Group B's Walk count?","explanation":"Group B's two cells must add to 24. Its Walk count is 24 - 9 = 15. Group A's values do not belong in this row calculation.","answer":15,"tolerance":0,"unit":"people","options":[]},
  {"slug":"change-d1","skill":"percentage-change","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"REMEMBER","difficulty":1,"prompt":"For a percentage increase from an original positive value to a new value, which quantity is the denominator?","explanation":"Percentage increase compares the amount gained with the original value: (new - original) / original times 100.","options":[{"content":"The new value","correct":false,"code":"CHANGE_FINAL_BASE"},{"content":"The increase alone","correct":false,"code":"CHANGE_DIFFERENCE_BASE"},{"content":"The sum of the original and new values","correct":false,"code":"CHANGE_SUM_BASE"},{"content":"The original value","correct":true}]},
  {"slug":"change-d2","skill":"percentage-change","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":4,"prompt":"A price rises by 20% and then falls by 20% of its new value. Compared with its starting price, it is now:","explanation":"The combined multiplier is 1.20 times 0.80 = 0.96. The final price is 96% of the starting price, a 4% decrease. The equal percentages use different bases.","options":[{"content":"4% lower","correct":true},{"content":"Unchanged","correct":false,"code":"SUCCESSIVE_PERCENTAGES_CANCEL"},{"content":"4% higher","correct":false,"code":"SUCCESSIVE_CHANGE_SIGN"},{"content":"40% lower","correct":false,"code":"SUCCESSIVE_PERCENTAGES_ADDED"}]},
  {"slug":"change-d3","skill":"percentage-change","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"UNDERSTAND","difficulty":2,"prompt":"A club grows from 50 members to 60 members. Select every correct description.","explanation":"The absolute increase is 10 members. Relative to the original 50, this is 10 / 50 = 20%. The final 60 is 120% of the original 50.","options":[{"content":"The club gained 10 members.","correct":true},{"content":"The club grew by 10%.","correct":false,"code":"ABSOLUTE_AS_PERCENT_CHANGE"},{"content":"The club grew by 20%.","correct":true},{"content":"The final size is 20% of the original size.","correct":false,"code":"CHANGE_AS_FINAL_PROPORTION"}]},
  {"slug":"change-d4","skill":"percentage-change","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"A survey share rises from 20% to 30%. Select every correct description of this change.","explanation":"Subtracting the shares gives 10 percentage points. Relative to the original 20%, the increase is 10 / 20 = 50%. The new share is 1.5 times the old share, not a 10% relative increase.","options":[{"content":"A relative increase of 10%","correct":false,"code":"POINTS_AS_RELATIVE_PERCENT"},{"content":"An increase of 10 percentage points","correct":true},{"content":"An increase of 50 percentage points","correct":false,"code":"RELATIVE_PERCENT_AS_POINTS"},{"content":"A relative increase of 50%","correct":true}]},
  {"slug":"change-d5","skill":"percentage-change","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":2,"prompt":"A price rises from 80 to 100. What is the percentage increase? Enter a number without the percent sign.","explanation":"The increase is 20 relative to the original 80: 20 / 80 times 100 = 25%.","answer":25,"tolerance":0,"unit":"percent","options":[]},
  {"slug":"change-d6","skill":"percentage-change","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":3,"prompt":"A water container's contents decrease from 250 litres to 200 litres. What is the percentage decrease? Enter the positive size of the decrease without a percent sign.","explanation":"The amount lost is 50 litres. Divide by the original 250 and multiply by 100: 50 / 250 times 100 = 20%.","answer":20,"tolerance":0,"unit":"percent","options":[]},
  {"slug":"mean-d1","skill":"arithmetic-mean","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"REMEMBER","difficulty":1,"prompt":"How do you calculate the arithmetic mean of a list of numbers?","explanation":"Add all observations and divide by the number of observations. The midpoint of the extremes, the median, and the most common value are different summaries.","options":[{"content":"Add the smallest and largest values, then divide by two.","correct":false,"code":"MIDRANGE_AS_MEAN"},{"content":"Add all values, then divide by how many values there are.","correct":true},{"content":"Sort the values and choose the middle one.","correct":false,"code":"MEDIAN_AS_MEAN"},{"content":"Choose the value appearing most often.","correct":false,"code":"MODE_AS_MEAN"}]},
  {"slug":"mean-d2","skill":"arithmetic-mean","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":4,"prompt":"Two learners average 10 minutes on an activity. Six other learners average 14 minutes. What is the mean time for all eight learners?","explanation":"The group totals are 2 times 10 = 20 and 6 times 14 = 84. Divide the combined 104 minutes by 8 learners to get 13 minutes. Averaging the two means equally ignores group sizes.","options":[{"content":"12 minutes","correct":false,"code":"UNWEIGHTED_GROUP_MEANS"},{"content":"24 minutes","correct":false,"code":"GROUP_MEANS_ADDED"},{"content":"13 minutes","correct":true},{"content":"3 minutes","correct":false,"code":"MEANS_SUM_DIVIDED_BY_COUNT"}]},
  {"slug":"mean-d3","skill":"arithmetic-mean","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"UNDERSTAND","difficulty":2,"prompt":"Consider the data 2, 4, and 9. Select every correct statement.","explanation":"The sum is 15 and there are 3 observations, so the mean is 5. A mean need not be an observed value and need not equal the middle value, which here is 4.","options":[{"content":"The total is 15.","correct":true},{"content":"The mean is 5.","correct":true},{"content":"The mean is 4 because 4 is the middle observation.","correct":false,"code":"MEDIAN_AS_MEAN"},{"content":"The mean must be one of 2, 4, or 9.","correct":false,"code":"MEAN_MUST_BE_OBSERVED"}]},
  {"slug":"mean-d4","skill":"arithmetic-mean","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Five readings have a mean of 12. Select every statement that must be true.","explanation":"The total is 5 times 12 = 60. Adding a sixth reading of 12 gives total 72 and mean 12. The existing readings need not all equal 12, and adding zero increases the count while leaving the total unchanged.","options":[{"content":"Every reading equals 12.","correct":false,"code":"MEAN_AS_EVERY_OBSERVATION"},{"content":"The readings total 60.","correct":true},{"content":"Adding a sixth reading of zero leaves the mean at 12.","correct":false,"code":"ZERO_EXCLUDED_FROM_COUNT"},{"content":"Adding a sixth reading of 12 leaves the mean at 12.","correct":true}]},
  {"slug":"mean-d5","skill":"arithmetic-mean","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":2,"prompt":"What is the arithmetic mean of 6, 8, 10, and 12?","explanation":"The total is 36 and there are 4 observations. The mean is 36 / 4 = 9.","answer":9,"tolerance":0,"unit":"units","options":[]},
  {"slug":"mean-d6","skill":"arithmetic-mean","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"ANALYZE","difficulty":3,"prompt":"Four daily counts have a mean of 15. Three counts are 11, 14, and 18. What is the fourth count?","explanation":"Four counts with mean 15 total 60. The known counts total 43, so the missing count is 60 - 43 = 17.","answer":17,"tolerance":0,"unit":"count","options":[]},
  {"slug":"median-d1","skill":"median-and-range","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"REMEMBER","difficulty":1,"prompt":"What is the range of a numerical data set?","explanation":"The range is the largest value minus the smallest value. It describes the span of the observations, not their count or their middle.","options":[{"content":"The middle value after sorting","correct":false,"code":"MEDIAN_AS_RANGE"},{"content":"The number of different values","correct":false,"code":"DISTINCT_COUNT_AS_RANGE"},{"content":"The sum divided by the count","correct":false,"code":"MEAN_AS_RANGE"},{"content":"The largest value minus the smallest value","correct":true}]},
  {"slug":"median-d2","skill":"median-and-range","purpose":"DIAGNOSTIC","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":4,"prompt":"The data are 2, 4, 5, 7, 12. If 12 is replaced by 30, what happens to the median and range?","explanation":"The middle observation remains 5. The range changes from 12 - 2 = 10 to 30 - 2 = 28. An endpoint can change the range without changing the median.","options":[{"content":"The median stays 5 and the range becomes 28.","correct":true},{"content":"The median becomes 16 and the range becomes 28.","correct":false,"code":"MIDRANGE_AS_MEDIAN"},{"content":"The median stays 5 and the range stays 10.","correct":false,"code":"RANGE_IGNORES_ENDPOINT_CHANGE"},{"content":"The median becomes 30 and the range becomes 30.","correct":false,"code":"MAXIMUM_AS_SUMMARIES"}]},
  {"slug":"median-d3","skill":"median-and-range","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"UNDERSTAND","difficulty":2,"prompt":"The observations are 8, 3, 5, 3, 11. Select every correct statement.","explanation":"Sorting without removing repetitions gives 3, 3, 5, 8, 11. The median is the third value, 5, and the range is 11 - 3 = 8. Repeated values still count as observations.","options":[{"content":"The sorted data are 3, 3, 5, 8, 11.","correct":true},{"content":"Remove the repeated 3 before locating the median.","correct":false,"code":"DUPLICATES_REMOVED"},{"content":"The median is 5.","correct":true},{"content":"The range is 11 because 11 is the largest value.","correct":false,"code":"MAXIMUM_AS_RANGE"}]},
  {"slug":"median-d4","skill":"median-and-range","purpose":"DIAGNOSTIC","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"The ordered data are 2, 4, 8, 10. Select every correct statement.","explanation":"With four observations, average the two middle values: (4 + 8) / 2 = 6. The range is 10 - 2 = 8. Neither middle observation alone is the even-count median.","options":[{"content":"The median is 4 because it is the first middle value.","correct":false,"code":"LOWER_MIDDLE_ONLY"},{"content":"The median is 6.","correct":true},{"content":"A median of 6 is impossible because 6 is not observed.","correct":false,"code":"MEDIAN_MUST_BE_OBSERVED"},{"content":"The range is 8.","correct":true}]},
  {"slug":"median-d5","skill":"median-and-range","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":2,"prompt":"Find the median of these five numbers: 14, 3, 9, 7, 12.","explanation":"Sort to get 3, 7, 9, 12, 14. The middle, third value is 9.","answer":9,"tolerance":0,"unit":"units","options":[]},
  {"slug":"median-d6","skill":"median-and-range","purpose":"DIAGNOSTIC","type":"NUMERIC","level":"APPLY","difficulty":3,"prompt":"Find the median of these six numbers: 13, 4, 8, 20, 6, 11.","explanation":"The sorted numbers are 4, 6, 8, 11, 13, 20. Average the third and fourth values: (8 + 11) / 2 = 9.5.","answer":9.5,"tolerance":0,"unit":"units","options":[]},
  {"slug":"rates-practice","skill":"unit-rates","purpose":"PRACTICE","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"Three litres of juice cost 84. At the same rate, what do 5 litres cost?","explanation":"The unit price is 84 / 3 = 28 per litre. Five litres cost 5 times 28 = 140.","options":[{"content":"140","correct":true},{"content":"420","correct":false,"code":"TOTAL_PRICE_AS_UNIT_RATE"},{"content":"86","correct":false,"code":"ADDITIVE_SCALING"},{"content":"50.4","correct":false,"code":"INVERTED_SCALE_FACTOR"}]},
  {"slug":"rates-assessment","skill":"unit-rates","purpose":"ASSESSMENT","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":3,"prompt":"A 1.5 kg bag costs 120 and a 2 kg bag costs 150. Which has the lower price per kilogram?","explanation":"The 1.5 kg bag costs 80 per kg and the 2 kg bag costs 75 per kg, so the 2 kg bag is cheaper per kilogram.","options":[{"content":"The 1.5 kg bag, at 80 per kg","correct":false,"code":"STICKER_PRICE_COMPARISON"},{"content":"The 2 kg bag, at 75 per kg","correct":true},{"content":"They are equal at 80 per kg","correct":false,"code":"DISTINCT_RATES_CONFLATED"},{"content":"The 2 kg bag, at 150 per kg","correct":false,"code":"TOTAL_AS_UNIT_RATE"}]},
  {"slug":"percent-practice","skill":"percentage-amounts","purpose":"PRACTICE","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"A 350 item has a 10% discount. What is the price paid?","explanation":"The discount is 35, so the price paid is 350 - 35 = 315. The discount amount is not the final price.","options":[{"content":"35","correct":false,"code":"DISCOUNT_AS_FINAL_PRICE"},{"content":"340","correct":false,"code":"PERCENT_AS_ABSOLUTE_AMOUNT"},{"content":"315","correct":true},{"content":"385","correct":false,"code":"DISCOUNT_ADDED"}]},
  {"slug":"percent-assessment","skill":"percentage-amounts","purpose":"ASSESSMENT","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"Twenty-four seats are 40% of all seats in a room. How many seats are there?","explanation":"If 0.40 of the total is 24, the total is 24 / 0.40 = 60 seats. Multiplying by 0.40 would calculate 40% of the part.","options":[{"content":"9.6","correct":false,"code":"PART_PERCENT_APPLIED_AGAIN"},{"content":"64","correct":false,"code":"PERCENT_AS_ABSOLUTE_AMOUNT"},{"content":"0.6","correct":false,"code":"PERCENT_NOT_CONVERTED"},{"content":"60","correct":true}]},
  {"slug":"tables-practice","skill":"reading-data-tables","purpose":"PRACTICE","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"A sales table records Monday: small boxes 8, large boxes 5; Tuesday: small boxes 12, large boxes 7. How many boxes of either size were sold on Tuesday?","explanation":"Use Tuesday's row: 12 + 7 = 19 boxes. The other day's values and the size-column totals answer different questions.","options":[{"content":"19","correct":true},{"content":"20","correct":false,"code":"COLUMN_TOTAL_FOR_ROW"},{"content":"13","correct":false,"code":"WRONG_ROW"},{"content":"32","correct":false,"code":"GRAND_TOTAL_FOR_ROW"}]},
  {"slug":"tables-assessment","skill":"reading-data-tables","purpose":"ASSESSMENT","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":3,"prompt":"A clinic records appointments, and one person can have several. Monday: morning 8, afternoon 7; Tuesday: morning 10, afternoon 5. Which statement is supported?","explanation":"Both days have 15 appointments. Appointment counts do not identify unique patients or causes of scheduling differences.","options":[{"content":"The clinic served exactly 30 different patients.","correct":false,"code":"EVENTS_AS_UNIQUE_PEOPLE"},{"content":"Both days had the same total appointment count.","correct":true},{"content":"Tuesday had more appointments because its morning count was larger.","correct":false,"code":"ONE_CELL_AS_TOTAL_COMPARISON"},{"content":"Every Monday patient returned on Tuesday.","correct":false,"code":"AGGREGATES_AS_PERSON_LINKS"}]},
  {"slug":"change-practice","skill":"percentage-change","purpose":"PRACTICE","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"A quantity increases from 120 to 150. What is the percentage increase?","explanation":"The gain is 30 out of the original 120: 30 / 120 times 100 = 25%.","options":[{"content":"20%","correct":false,"code":"CHANGE_FINAL_BASE"},{"content":"30%","correct":false,"code":"ABSOLUTE_AS_PERCENT_CHANGE"},{"content":"25%","correct":true},{"content":"125%","correct":false,"code":"FINAL_PROPORTION_AS_CHANGE"}]},
  {"slug":"change-assessment","skill":"percentage-change","purpose":"ASSESSMENT","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":3,"prompt":"A survey share falls from 40% to 30%. Which description is correct?","explanation":"The share falls by 10 percentage points. Relative to the original 40%, the fall is 10 / 40 = 25%.","options":[{"content":"A fall of 10 percentage points and a relative fall of 10%","correct":false,"code":"POINTS_AS_RELATIVE_PERCENT"},{"content":"A fall of 25 percentage points and a relative fall of 10%","correct":false,"code":"POINTS_RELATIVE_SWAPPED"},{"content":"A fall of 10 percentage points and a relative fall of 33.3%","correct":false,"code":"CHANGE_FINAL_BASE"},{"content":"A fall of 10 percentage points and a relative fall of 25%","correct":true}]},
  {"slug":"mean-practice","skill":"arithmetic-mean","purpose":"PRACTICE","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"What is the arithmetic mean of 0, 6, and 12?","explanation":"The total is 18 across 3 observations, including zero. The mean is 6. Excluding zero from the count would incorrectly give 9.","options":[{"content":"6","correct":true},{"content":"9","correct":false,"code":"ZERO_EXCLUDED_FROM_COUNT"},{"content":"18","correct":false,"code":"SUM_AS_MEAN"},{"content":"12","correct":false,"code":"MAXIMUM_AS_MEAN"}]},
  {"slug":"mean-assessment","skill":"arithmetic-mean","purpose":"ASSESSMENT","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":3,"prompt":"Three measurements have a mean of 8. A fourth measurement is 12. What is the mean of all four?","explanation":"The first three measurements total 24. Adding 12 gives 36 across 4 measurements, with mean 9. Averaging 8 and 12 equally ignores the three original observations.","options":[{"content":"10","correct":false,"code":"UNWEIGHTED_GROUP_MEANS"},{"content":"9","correct":true},{"content":"5","correct":false,"code":"MEANS_SUM_DIVIDED_BY_COUNT"},{"content":"12","correct":false,"code":"NEW_VALUE_AS_MEAN"}]},
  {"slug":"median-practice","skill":"median-and-range","purpose":"PRACTICE","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"What is the range of 7, 2, 9, 4, and 2?","explanation":"The maximum is 9 and minimum is 2, so the range is 9 - 2 = 7. Repetition of the minimum does not change the endpoints.","options":[{"content":"9","correct":false,"code":"MAXIMUM_AS_RANGE"},{"content":"5","correct":false,"code":"COUNT_AS_RANGE"},{"content":"7","correct":true},{"content":"4","correct":false,"code":"MEDIAN_AS_RANGE"}]},
  {"slug":"median-assessment","skill":"median-and-range","purpose":"ASSESSMENT","type":"SINGLE_CHOICE","level":"ANALYZE","difficulty":3,"prompt":"For the ordered data 1, 4, 7, 10, what are the median and range?","explanation":"The median averages the two middle values: (4 + 7) / 2 = 5.5. The range is 10 - 1 = 9.","options":[{"content":"Median 4; range 9","correct":false,"code":"LOWER_MIDDLE_ONLY"},{"content":"Median 7; range 9","correct":false,"code":"UPPER_MIDDLE_ONLY"},{"content":"Median 5.5; range 10","correct":false,"code":"MAXIMUM_AS_RANGE"},{"content":"Median 5.5; range 9","correct":true}]}
]
$quant_questions$::jsonb) AS content(slug text, skill text, purpose text, type text, level text, difficulty integer,
  prompt text, explanation text, options jsonb, answer double precision, tolerance double precision, unit text);

INSERT INTO questions (id, skill_id, slug, prompt, question_type, difficulty, explanation, status,
  question_purpose, cognitive_level, discrimination, guess_probability, calibration_state,
  expected_response_seconds, numeric_answer, numeric_tolerance, numeric_unit)
SELECT md5('learnpath:quant:question:' || slug)::uuid, md5('learnpath:quant:skill:' || skill)::uuid,
  'quant-' || slug, prompt, type, difficulty, explanation, 'ACTIVE', purpose, level,
  1.0, CASE type WHEN 'NUMERIC' THEN 0.0 WHEN 'MULTI_SELECT' THEN 0.067 ELSE 0.25 END,
  'EXPERT_PRIOR', CASE level WHEN 'REMEMBER' THEN 25 WHEN 'UNDERSTAND' THEN 40 WHEN 'APPLY' THEN 60 ELSE 90 END,
  answer, tolerance, unit FROM quant_questions;

INSERT INTO question_options (id, question_id, option_key, content, is_correct, misconception_code)
SELECT md5('learnpath:quant:option:' || question.slug || ':' || option.ordinality)::uuid,
  md5('learnpath:quant:question:' || question.slug)::uuid, chr(64 + option.ordinality::integer),
  option.value->>'content', (option.value->>'correct')::boolean, option.value->>'code'
FROM quant_questions question CROSS JOIN LATERAL jsonb_array_elements(question.options) WITH ORDINALITY AS option(value, ordinality);

-- Each item supplies attributable evidence for exactly one primary skill.
-- No secondary-skill mastery is inferred from a composite prompt.
INSERT INTO question_skill_mappings (question_id, skill_id, mapping_type, evidence_weight)
SELECT md5('learnpath:quant:question:' || slug)::uuid, md5('learnpath:quant:skill:' || skill)::uuid,
  'PRIMARY', 1.0 FROM quant_questions;

INSERT INTO assessments (id, course_id, title, description, assessment_type, status, estimated_minutes)
VALUES (md5('learnpath:quant:diagnostic')::uuid, md5('learnpath:quant:course')::uuid,
  'Everyday Quantitative Reasoning Diagnostic',
  'A 36-item bank across six assessable skills, sampled over bounded sessions. Course coverage is distinct from mastery. Item parameters are provisional author priors, not empirical calibration.',
  'DIAGNOSTIC', 'ACTIVE', 18);

INSERT INTO assessment_questions (assessment_id, question_id, sequence)
SELECT md5('learnpath:quant:diagnostic')::uuid, md5('learnpath:quant:question:' || question.slug)::uuid,
  ROW_NUMBER() OVER (ORDER BY module.sequence, skill.sequence, question.slug)::smallint
FROM quant_questions question JOIN quant_skills skill ON skill.slug = question.skill
JOIN modules module ON module.id = md5('learnpath:quant:module:' || skill.module)::uuid
WHERE question.purpose = 'DIAGNOSTIC';

INSERT INTO learning_resources (id, slug, title, summary, resource_type, difficulty, estimated_minutes,
  learning_objectives, content_sections)
SELECT md5('learnpath:quant:resource:' || skill.slug || ':' || (lesson.value->>'type'))::uuid,
  'quant-' || skill.slug || '-' || replace(lower(lesson.value->>'type'), '_', '-'), lesson.value->>'title', lesson.value->>'summary',
  lesson.value->>'type', skill.difficulty, CASE WHEN lesson.value->>'type' = 'CONCEPT_GUIDE' THEN 12 ELSE 10 END,
  ARRAY(SELECT jsonb_array_elements_text(lesson.value->'objectives')), lesson.value->'sections'
FROM quant_skills skill CROSS JOIN LATERAL jsonb_array_elements(skill.lessons) AS lesson(value);

INSERT INTO learning_resource_skills (resource_id, skill_id, is_primary)
SELECT md5('learnpath:quant:resource:' || skill.slug || ':' || (lesson.value->>'type'))::uuid,
  md5('learnpath:quant:skill:' || skill.slug)::uuid, TRUE
FROM quant_skills skill CROSS JOIN LATERAL jsonb_array_elements(skill.lessons) AS lesson(value);

INSERT INTO learning_resource_contexts (resource_id, course_id, module_id)
SELECT md5('learnpath:quant:resource:' || skill.slug || ':' || (lesson.value->>'type'))::uuid,
  md5('learnpath:quant:course')::uuid, md5('learnpath:quant:module:' || skill.module)::uuid
FROM quant_skills skill CROSS JOIN LATERAL jsonb_array_elements(skill.lessons) AS lesson(value);

INSERT INTO system_metadata (key, value) VALUES ('quantitative_reasoning_content', jsonb_build_object(
  'version', 'original-demonstration-v1', 'courseSlug', 'everyday-quantitative-reasoning',
  'skills', 6, 'modules', 3, 'diagnosticQuestions', 36, 'practiceQuestions', 6,
  'postLessonAssessmentQuestions', 6, 'learningResources', 12,
  'authoringStatus', 'Original authored demonstration; expert review and empirical calibration pending.',
  'measurementNote', 'EXPERT_PRIOR is the schema label for provisional author priors and does not certify expert validation.'
));

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM quant_skills) <> 6
    OR (SELECT COUNT(*) FROM quant_questions WHERE purpose = 'DIAGNOSTIC') <> 36
    OR EXISTS (
      SELECT skill, type FROM quant_questions WHERE purpose = 'DIAGNOSTIC'
      GROUP BY skill, type HAVING COUNT(*) <> 2
    ) THEN RAISE EXCEPTION 'Quantitative reasoning content manifest is incomplete'; END IF;
END $$;
