-- Reframe the curriculum around observable diagnostic evidence. Historical
-- attempts remain unchanged because they use immutable question snapshots.

ALTER TABLE questions
  ADD COLUMN diagnostic_role TEXT NOT NULL DEFAULT 'ANCHOR',
  ADD COLUMN construct_code TEXT NOT NULL DEFAULT 'FOUNDATION',
  ADD COLUMN content_version INTEGER NOT NULL DEFAULT 1,
  ADD CONSTRAINT questions_diagnostic_role_allowed CHECK (
    diagnostic_role IN ('ANCHOR', 'VERIFICATION', 'CHALLENGE')
  ),
  ADD CONSTRAINT questions_content_version_positive CHECK (content_version > 0);

CREATE TABLE skill_diagnostic_blueprints (
  skill_id UUID PRIMARY KEY REFERENCES skills(id) ON DELETE CASCADE,
  anchor_objective TEXT NOT NULL,
  application_objective TEXT NOT NULL,
  boundary_objective TEXT NOT NULL,
  minimum_direct_observations SMALLINT NOT NULL DEFAULT 3,
  minimum_cognitive_levels SMALLINT NOT NULL DEFAULT 2,
  minimum_difficulty_bands SMALLINT NOT NULL DEFAULT 2,
  requires_application_evidence BOOLEAN NOT NULL DEFAULT TRUE,
  blueprint_version INTEGER NOT NULL DEFAULT 2,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT skill_diagnostic_blueprint_minima CHECK (
    minimum_direct_observations >= 2
    AND minimum_cognitive_levels >= 2
    AND minimum_difficulty_bands >= 2
    AND blueprint_version > 0
  )
);

INSERT INTO skill_diagnostic_blueprints (
  skill_id, anchor_objective, application_objective, boundary_objective
)
SELECT id,
       'Distinguish the essential meaning and invariant of ' || name || ' from plausible misconceptions.',
       'Apply ' || name || ' correctly in a representative course scenario.',
       'Identify when ' || name || ' is valid, insufficient, or inappropriate under changed constraints.'
FROM skills
WHERE is_active;

-- Retire the synthetic application templates. They remain in the database for
-- auditability and historical foreign keys but cannot be selected again.
UPDATE questions
SET status = 'RETIRED', updated_at = NOW()
WHERE slug LIKE 'adaptive-%-application-v2';

UPDATE questions
SET diagnostic_role = CASE
      WHEN question_type = 'MULTI_SELECT' OR cognitive_level = 'ANALYZE' THEN 'CHALLENGE'
      WHEN question_type = 'NUMERIC' OR cognitive_level = 'APPLY' THEN 'VERIFICATION'
      ELSE 'ANCHOR'
    END,
    construct_code = CASE
      WHEN question_type = 'MULTI_SELECT' OR cognitive_level = 'ANALYZE' THEN 'BOUNDARY'
      WHEN question_type = 'NUMERIC' OR cognitive_level = 'APPLY' THEN 'APPLICATION'
      ELSE 'FOUNDATION'
    END,
    content_version = 2
WHERE status = 'ACTIVE' AND question_purpose = 'DIAGNOSTIC';

WITH authored AS (
  SELECT * FROM jsonb_to_recordset($bank$
  [
    {"slug":"arrays-application-v2","skill":"arrays","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"An array contains [4, 7, 9, 12]. After inserting 5 at index 1, which sequence is correct?","explanation":"Insertion at index 1 shifts the existing suffix right, producing [4, 5, 7, 9, 12].","options":[{"c":"[4, 5, 7, 9, 12]","ok":true},{"c":"[5, 4, 7, 9, 12]","ok":false,"code":"ARRAY_INSERT_AS_PREPEND"},{"c":"[4, 7, 5, 9, 12]","ok":false,"code":"ARRAY_INDEX_OFF_BY_ONE"},{"c":"[4, 7, 9, 12, 5]","ok":false,"code":"ARRAY_INSERT_AS_APPEND"}]},
    {"slug":"arrays-boundary-v2","skill":"arrays","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every operation that is O(1) for a standard contiguous array when capacity is already available.","explanation":"Indexed read and replacement use direct address calculation. Front insertion and searching an unsorted array can require linear work.","options":[{"c":"Read the element at a known valid index","ok":true},{"c":"Replace the element at a known valid index","ok":true},{"c":"Insert at the beginning while preserving order","ok":false,"code":"ARRAY_SHIFT_IGNORED"},{"c":"Find an unknown value in an unsorted array","ok":false,"code":"ARRAY_SEARCH_ASSUMED_CONSTANT"}]},

    {"slug":"backtracking-application-v2","skill":"backtracking","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"While generating valid arrangements, a partial choice already violates a constraint. What should a backtracking solver do next?","explanation":"It should undo the most recent choice and try the next candidate; continuing cannot make an invalid prefix valid.","options":[{"c":"Undo the choice and try another candidate","ok":true},{"c":"Continue until a complete arrangement is produced","ok":false,"code":"BACKTRACKING_NO_PRUNING"},{"c":"Restart the entire search from the root","ok":false,"code":"BACKTRACKING_FULL_RESTART"},{"c":"Accept the prefix because later choices may erase it","ok":false,"code":"BACKTRACKING_INVALID_PREFIX"}]},
    {"slug":"backtracking-boundary-v2","skill":"backtracking","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every property of a correct backtracking solution for placing non-attacking queens.","explanation":"A solver explores choices, rejects invalid partial boards early, and restores state before trying alternatives. Greedy commitment is not guaranteed to work.","options":[{"c":"Reject a partial board as soon as two queens attack","ok":true},{"c":"Restore the board after returning from a recursive branch","ok":true},{"c":"Keep the first locally safe position permanently","ok":false,"code":"BACKTRACKING_AS_GREEDY"},{"c":"Enumerate extensions of an already invalid prefix","ok":false,"code":"BACKTRACKING_NO_PRUNING"}]},

    {"slug":"basic-sorting-application-v2","skill":"basic-sorting","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"After the first complete pass of bubble sort on [5, 1, 4, 2], what is the array?","explanation":"Adjacent inversions are swapped: [1,5,4,2], then [1,4,5,2], then [1,4,2,5].","options":[{"c":"[1, 4, 2, 5]","ok":true},{"c":"[1, 2, 4, 5]","ok":false,"code":"BUBBLE_ONE_PASS_AS_COMPLETE"},{"c":"[5, 1, 2, 4]","ok":false,"code":"BUBBLE_WRONG_DIRECTION"},{"c":"[1, 5, 4, 2]","ok":false,"code":"BUBBLE_SINGLE_SWAP_ONLY"}]},
    {"slug":"basic-sorting-boundary-v2","skill":"basic-sorting","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every true statement about insertion sort.","explanation":"Insertion sort maintains a sorted prefix, is quadratic in the worst case, and performs well on nearly sorted small inputs. It does not require all pairs to be compared.","options":[{"c":"It maintains a sorted prefix","ok":true},{"c":"Its worst-case running time is O(n squared)","ok":true},{"c":"It must compare every possible pair","ok":false,"code":"INSERTION_ALL_PAIRS"},{"c":"It is always faster than O(n log n) sorting","ok":false,"code":"INSERTION_UNIVERSALLY_FAST"}]},

    {"slug":"binary-search-application-v2","skill":"binary-search","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"Binary search examines 14 in [2, 5, 9, 14, 20, 27, 31]. Which condition permits discarding the left half?","explanation":"If the target is greater than the middle value, every earlier sorted value is too small.","options":[{"c":"The target is greater than the middle value","ok":true},{"c":"The target differs from the middle value","ok":false,"code":"BINARY_SEARCH_DISCARD_ARBITRARY_HALF"},{"c":"The array has an odd length","ok":false,"code":"BINARY_SEARCH_PARITY_RULE"},{"c":"The target is smaller than the final value","ok":false,"code":"BINARY_SEARCH_USES_ENDPOINT_ONLY"}]},
    {"slug":"binary-search-boundary-v2","skill":"binary-search","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every situation where ordinary binary search is directly valid.","explanation":"Binary search requires an ordered search space and a monotonic decision. An unsorted array or arbitrary linked-list access violates those assumptions.","options":[{"c":"Finding a value in a sorted random-access array","ok":true},{"c":"Finding the first feasible value of a monotonic predicate","ok":true},{"c":"Finding a value in an unsorted array without preprocessing","ok":false,"code":"BINARY_SEARCH_IGNORES_ORDER"},{"c":"Repeatedly accessing the middle of a singly linked list in O(1)","ok":false,"code":"BINARY_SEARCH_IGNORES_ACCESS_COST"}]},

    {"slug":"binary-search-trees-application-v2","skill":"binary-search-trees","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"A BST contains 8 at the root, 3 on the left, and 10 on the right. Where is key 6 searched after comparing with 8 and then 3?","explanation":"Six is less than 8 but greater than 3, so search continues into the right subtree of node 3.","options":[{"c":"The right subtree of 3","ok":true},{"c":"The left subtree of 3","ok":false,"code":"BST_COMPARISON_REVERSED"},{"c":"The right subtree of 10","ok":false,"code":"BST_ROOT_DECISION_IGNORED"},{"c":"Both subtrees of 3","ok":false,"code":"BST_SEARCHES_BOTH_BRANCHES"}]},
    {"slug":"binary-search-trees-boundary-v2","skill":"binary-search-trees","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every true statement about an unbalanced binary search tree.","explanation":"In-order traversal stays sorted, but height may become n and operations may degrade to O(n). The BST invariant is local to every node.","options":[{"c":"In-order traversal produces keys in sorted order","ok":true},{"c":"Search can degrade to O(n)","ok":true},{"c":"Its height is always logarithmic","ok":false,"code":"BST_ASSUMED_BALANCED"},{"c":"Only the root must satisfy the ordering rule","ok":false,"code":"BST_INVARIANT_ROOT_ONLY"}]},

    {"slug":"binary-trees-application-v2","skill":"binary-trees","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"A binary tree has root A, children B and C, and B has left child D. What is its preorder traversal?","explanation":"Preorder visits root, then left subtree, then right subtree: A, B, D, C.","options":[{"c":"A, B, D, C","ok":true},{"c":"D, B, A, C","ok":false,"code":"TREE_PREORDER_AS_INORDER"},{"c":"D, B, C, A","ok":false,"code":"TREE_PREORDER_AS_POSTORDER"},{"c":"A, C, B, D","ok":false,"code":"TREE_CHILD_ORDER_REVERSED"}]},
    {"slug":"binary-trees-boundary-v2","skill":"binary-trees","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every fact guaranteed for all binary trees with n greater than zero.","explanation":"Every node has at most two children and a tree with n nodes has n minus 1 edges. Binary trees need not be balanced, complete, or ordered.","options":[{"c":"Every node has at most two children","ok":true},{"c":"The tree has n minus 1 edges","ok":true},{"c":"The height is always O(log n)","ok":false,"code":"BINARY_TREE_ASSUMED_BALANCED"},{"c":"Left descendants are always smaller","ok":false,"code":"BINARY_TREE_AS_BST"}]},

    {"slug":"bit-manipulation-application-v2","skill":"bit-manipulation","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"Which expression clears bit k of integer x while leaving other bits unchanged?","explanation":"A mask with zero only at bit k is produced by complementing 1 shifted by k; AND clears that bit.","options":[{"c":"x AND NOT (1 shifted left by k)","ok":true},{"c":"x OR (1 shifted left by k)","ok":false,"code":"BIT_CLEAR_AS_SET"},{"c":"x XOR 0","ok":false,"code":"BIT_CLEAR_XOR_ZERO"},{"c":"x AND (1 shifted left by k)","ok":false,"code":"BIT_CLEAR_ISOLATES_BIT"}]},
    {"slug":"bit-manipulation-boundary-v2","skill":"bit-manipulation","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every expression that is true for a positive power-of-two integer x.","explanation":"A power of two has one set bit, so x AND (x minus 1) is zero and its set-bit count is one.","options":[{"c":"x AND (x minus 1) equals zero","ok":true},{"c":"The number of set bits in x is one","ok":true},{"c":"x AND 1 is always one","ok":false,"code":"POWER_TWO_ALWAYS_ODD"},{"c":"x XOR x equals x","ok":false,"code":"XOR_SELF_MISUNDERSTOOD"}]},

    {"slug":"breadth-first-search-application-v2","skill":"breadth-first-search","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"In an unweighted graph, when should a vertex normally be marked visited during BFS?","explanation":"Marking it when enqueued prevents multiple parents from adding the same vertex before it is processed.","options":[{"c":"When it is enqueued","ok":true},{"c":"Only after all its neighbors are processed","ok":false,"code":"BFS_VISITED_TOO_LATE"},{"c":"Whenever it is dequeued, even repeatedly","ok":false,"code":"BFS_DUPLICATE_ENQUEUE"},{"c":"Only if it has no outgoing edges","ok":false,"code":"BFS_VISITED_LEAVES_ONLY"}]},
    {"slug":"breadth-first-search-boundary-v2","skill":"breadth-first-search","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every problem BFS solves correctly without modifying its priority rule.","explanation":"BFS finds minimum-edge distances and explores tree levels. Arbitrary weighted shortest paths need a weight-aware algorithm, and topological sorting also requires indegree logic.","options":[{"c":"Minimum-edge distance from a source in an unweighted graph","ok":true},{"c":"Level-order traversal of a tree","ok":true},{"c":"Shortest paths with arbitrary positive edge weights","ok":false,"code":"BFS_IGNORES_EDGE_WEIGHTS"},{"c":"Topological order of any directed graph without indegrees","ok":false,"code":"BFS_AS_TOPOLOGICAL_SORT"}]},

    {"slug":"complexity-analysis-application-v2","skill":"complexity-analysis","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"An algorithm halves n until it reaches 1 and performs constant work each step. What is its time complexity?","explanation":"The number of halvings is logarithmic, so total time is O(log n).","options":[{"c":"O(log n)","ok":true},{"c":"O(n)","ok":false,"code":"HALVING_AS_LINEAR"},{"c":"O(n log n)","ok":false,"code":"LOG_LOOP_EXTRA_N"},{"c":"O(1)","ok":false,"code":"REPEATED_CONSTANT_AS_CONSTANT"}]},
    {"slug":"complexity-analysis-boundary-v2","skill":"complexity-analysis","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every statement justified by asymptotic analysis.","explanation":"Big-O describes growth bounds and constants are omitted, but input representation and average versus worst case still matter.","options":[{"c":"O(n) and O(2n plus 10) have the same growth class","ok":true},{"c":"Worst-case and average-case bounds can differ","ok":true},{"c":"An O(n) algorithm is faster for every input size than every O(n squared) algorithm","ok":false,"code":"ASYMPTOTIC_ALWAYS_FASTER"},{"c":"Input representation never affects complexity","ok":false,"code":"COMPLEXITY_IGNORES_REPRESENTATION"}]},

    {"slug":"control-flow-application-v2","skill":"control-flow","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"A loop should process values until the first negative number, without processing that negative value. Where should the condition be checked?","explanation":"Checking before processing and breaking immediately prevents the sentinel value from being handled.","options":[{"c":"Before processing each value, break if it is negative","ok":true},{"c":"After processing every value, including the negative one","ok":false,"code":"SENTINEL_PROCESSED"},{"c":"Only after the entire loop finishes","ok":false,"code":"BREAK_AFTER_LOOP"},{"c":"Use no condition because the data will stop itself","ok":false,"code":"LOOP_WITHOUT_TERMINATION"}]},
    {"slug":"control-flow-boundary-v2","skill":"control-flow","type":"MULTI_SELECT","level":"ANALYZE","difficulty":3,"prompt":"Select every condition that can cause an intended while loop to become infinite.","explanation":"A loop may never end if its controlling state is not updated or if the termination condition is unreachable. Multiple iterations alone do not imply infinity.","options":[{"c":"The condition variable is never updated","ok":true},{"c":"The update moves the variable away from the stopping value","ok":true},{"c":"The loop executes more than once","ok":false,"code":"LOOP_REPETITION_AS_INFINITE"},{"c":"The body contains an if statement","ok":false,"code":"IF_CAUSES_INFINITE_LOOP"}]},

    {"slug":"depth-first-search-application-v2","skill":"depth-first-search","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"A recursive DFS enters vertex v. What must it do before recursively visiting an unvisited neighbor in a cyclic graph?","explanation":"Marking v visited before recursion prevents a neighbor from immediately traversing back to v indefinitely.","options":[{"c":"Mark v visited","ok":true},{"c":"Remove every edge incident to v","ok":false,"code":"DFS_MUTATES_GRAPH"},{"c":"Sort all vertices globally","ok":false,"code":"DFS_REQUIRES_SORT"},{"c":"Finish the entire connected component first","ok":false,"code":"DFS_VISITED_AFTER_COMPONENT"}]},
    {"slug":"depth-first-search-boundary-v2","skill":"depth-first-search","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every task for which DFS is a natural component of a correct solution.","explanation":"DFS supports component discovery and cycle detection with state tracking. Plain DFS does not guarantee weighted shortest paths or ascending vertex order.","options":[{"c":"Finding connected components","ok":true},{"c":"Detecting a cycle with appropriate visitation states","ok":true},{"c":"Finding shortest paths in arbitrary weighted graphs","ok":false,"code":"DFS_AS_WEIGHTED_SHORTEST_PATH"},{"c":"Guaranteeing vertices are visited in numeric order","ok":false,"code":"DFS_ORDER_GUARANTEE"}]},

    {"slug":"divide-and-conquer-application-v2","skill":"divide-and-conquer","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"Merge sort splits an input into halves, recursively sorts them, and merges in linear time. Which recurrence describes it?","explanation":"There are two subproblems of half size and linear combine work: T(n) = 2T(n/2) + O(n).","options":[{"c":"T(n) = 2T(n/2) + O(n)","ok":true},{"c":"T(n) = T(n minus 1) + O(1)","ok":false,"code":"DIVIDE_AS_DECREMENT"},{"c":"T(n) = nT(n/2)","ok":false,"code":"SUBPROBLEM_COUNT_AS_N"},{"c":"T(n) = T(n/2) + O(1)","ok":false,"code":"MERGESORT_ONE_BRANCH"}]},
    {"slug":"divide-and-conquer-boundary-v2","skill":"divide-and-conquer","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every feature required for a useful divide-and-conquer design.","explanation":"The problem is split into smaller instances, their solutions are combined, and recursion must reach a base case. Subproblems need not always be disjoint.","options":[{"c":"Subproblems are smaller than the original","ok":true},{"c":"A base case stops recursive division","ok":true},{"c":"Subproblems must always be completely disjoint","ok":false,"code":"DIVIDE_REQUIRES_DISJOINT"},{"c":"The combine step must be constant time","ok":false,"code":"DIVIDE_COMBINE_CONSTANT_ONLY"}]},

    {"slug":"dynamic-programming-foundations-application-v2","skill":"dynamic-programming-foundations","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"A recursive solution repeatedly solves the same state defined by index i and remaining capacity c. What is the most important DP design step?","explanation":"The state must be defined by every value that changes future outcomes, here both i and c, so repeated states can be reused.","options":[{"c":"Represent the state by both i and c","ok":true},{"c":"Cache only by i because it is shorter","ok":false,"code":"DP_INCOMPLETE_STATE"},{"c":"Remove all base cases","ok":false,"code":"DP_WITHOUT_BASE_CASE"},{"c":"Sort answers after recursion finishes","ok":false,"code":"DP_AS_OUTPUT_SORT"}]},
    {"slug":"dynamic-programming-foundations-boundary-v2","skill":"dynamic-programming-foundations","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every signal that dynamic programming may be appropriate.","explanation":"DP is useful when subproblems overlap and an optimal or counting solution can be composed from smaller states. Recursion alone and greedy-choice availability are not sufficient.","options":[{"c":"The same state is solved repeatedly","ok":true},{"c":"A solution can be composed from smaller-state solutions","ok":true},{"c":"The problem can be written recursively","ok":false,"code":"DP_ANY_RECURSION"},{"c":"A locally best choice is always globally best","ok":false,"code":"DP_CONFUSED_WITH_GREEDY"}]},

    {"slug":"efficient-sorting-application-v2","skill":"efficient-sorting","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"Quicksort repeatedly receives partitions of sizes zero and n minus 1. What total time does this imply?","explanation":"The highly unbalanced recurrence performs roughly n plus n minus 1 plus further work, giving O(n squared).","options":[{"c":"O(n squared)","ok":true},{"c":"O(n log n)","ok":false,"code":"QUICKSORT_ALWAYS_N_LOG_N"},{"c":"O(log n)","ok":false,"code":"QUICKSORT_RECURSION_ONLY"},{"c":"O(n)","ok":false,"code":"QUICKSORT_SINGLE_PARTITION"}]},
    {"slug":"efficient-sorting-boundary-v2","skill":"efficient-sorting","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every true comparison between merge sort and typical in-place quicksort.","explanation":"Merge sort guarantees O(n log n) time and normally needs auxiliary merge storage; typical in-place quicksort has quadratic worst case but often low extra array storage.","options":[{"c":"Merge sort guarantees O(n log n) worst-case time","ok":true},{"c":"Typical in-place quicksort can have O(n squared) worst-case time","ok":true},{"c":"Merge sort always uses O(1) extra space for arrays","ok":false,"code":"MERGESORT_IN_PLACE_ASSUMED"},{"c":"Quicksort is stable for every ordinary implementation","ok":false,"code":"QUICKSORT_ALWAYS_STABLE"}]},

    {"slug":"functions-application-v2","skill":"functions","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"A function changes its local parameter x, but the caller passed an immutable number value. What should the caller expect after the function returns?","explanation":"Reassigning the local parameter does not reassign the caller variable when the value is passed by value.","options":[{"c":"The caller variable is unchanged","ok":true},{"c":"The caller variable must take the local value","ok":false,"code":"PARAMETER_REASSIGN_MUTATES_CALLER"},{"c":"The function cannot use x","ok":false,"code":"PARAMETER_NOT_LOCAL"},{"c":"Every call returns the changed x automatically","ok":false,"code":"IMPLICIT_RETURN_ASSUMED"}]},
    {"slug":"functions-boundary-v2","skill":"functions","type":"MULTI_SELECT","level":"ANALYZE","difficulty":3,"prompt":"Select every benefit of giving a function one clear responsibility with explicit inputs and outputs.","explanation":"Clear contracts improve independent testing and reuse. They do not remove all errors or make shared global state safer.","options":[{"c":"It can be tested independently more easily","ok":true},{"c":"Its behavior is easier to reuse and reason about","ok":true},{"c":"It guarantees that the function contains no defect","ok":false,"code":"FUNCTION_STRUCTURE_GUARANTEES_CORRECTNESS"},{"c":"It makes hidden global dependencies desirable","ok":false,"code":"FUNCTION_GLOBAL_COUPLING"}]},

    {"slug":"graph-fundamentals-application-v2","skill":"graph-fundamentals","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"An undirected graph has vertex degrees 2, 3, 1, and 2. How many edges does it contain?","explanation":"The degree sum is 8. Each undirected edge contributes two to that sum, so there are 4 edges.","options":[{"c":"4","ok":true},{"c":"8","ok":false,"code":"GRAPH_DEGREE_SUM_AS_EDGES"},{"c":"3","ok":false,"code":"GRAPH_MAX_DEGREE_AS_EDGES"},{"c":"2","ok":false,"code":"GRAPH_VERTEX_PAIRING"}]},
    {"slug":"graph-fundamentals-boundary-v2","skill":"graph-fundamentals","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every true statement for a simple undirected graph.","explanation":"Edges have no orientation and degree counts incident edges. A graph may be disconnected or cyclic, and adjacency need not be transitive.","options":[{"c":"Each edge contributes one to the degree of both endpoints","ok":true},{"c":"An adjacency list can represent the graph","ok":true},{"c":"Every pair of vertices has a path between them","ok":false,"code":"GRAPH_ASSUMED_CONNECTED"},{"c":"If A touches B and B touches C, A must touch C","ok":false,"code":"GRAPH_ADJACENCY_TRANSITIVE"}]},

    {"slug":"hashing-application-v2","skill":"hashing","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"A hash table using separate chaining has many keys in one bucket. Which change most directly reduces expected chain length?","explanation":"Increasing capacity and rehashing lowers the load factor when the hash function distributes keys adequately.","options":[{"c":"Increase capacity and rehash the keys","ok":true},{"c":"Sort each key before hashing","ok":false,"code":"HASHING_SORT_KEYS"},{"c":"Remove collision handling","ok":false,"code":"HASHING_COLLISIONS_IGNORED"},{"c":"Always map new keys to the fullest bucket","ok":false,"code":"HASHING_REVERSED_DISTRIBUTION"}]},
    {"slug":"hashing-boundary-v2","skill":"hashing","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every requirement for keys used safely in a hash-based map.","explanation":"Equal keys must have equal hashes and a key's equality-relevant state must remain stable while stored. Different keys may collide.","options":[{"c":"Equal keys produce equal hash values","ok":true},{"c":"A stored key does not change in a way that changes equality or hash","ok":true},{"c":"Different keys must always have different hashes","ok":false,"code":"HASHING_NO_COLLISIONS_POSSIBLE"},{"c":"Hash values must preserve key ordering","ok":false,"code":"HASHING_AS_ORDERED_MAP"}]},

    {"slug":"heaps-application-v2","skill":"heaps","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"A min-heap root is removed. Which element normally moves to the root before heap order is restored?","explanation":"The last element fills the root vacancy, then sifts down to restore the heap property while preserving completeness.","options":[{"c":"The last element in the heap array","ok":true},{"c":"The largest element","ok":false,"code":"MIN_HEAP_REPLACE_WITH_MAX"},{"c":"The root's left child without moving anything else","ok":false,"code":"HEAP_COMPLETENESS_IGNORED"},{"c":"A randomly chosen leaf","ok":false,"code":"HEAP_RANDOM_REPLACEMENT"}]},
    {"slug":"heaps-boundary-v2","skill":"heaps","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every operation supported efficiently by a binary min-heap.","explanation":"Reading the minimum is O(1), while insertion and removing the minimum are O(log n). Searching for an arbitrary value is not generally logarithmic.","options":[{"c":"Read the minimum in O(1)","ok":true},{"c":"Insert a value in O(log n)","ok":true},{"c":"Find any arbitrary value in O(log n)","ok":false,"code":"HEAP_AS_SEARCH_TREE"},{"c":"Produce all values sorted in O(n) total time","ok":false,"code":"HEAP_SORT_LINEAR"}]},

    {"slug":"knapsack-patterns-application-v2","skill":"knapsack-patterns","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"In 0/1 knapsack, why is the one-dimensional capacity array commonly updated from high capacity to low capacity?","explanation":"Descending updates prevent an item written in the current iteration from being reused again, preserving the 0/1 constraint.","options":[{"c":"To prevent using the same item more than once","ok":true},{"c":"To make item weights sorted","ok":false,"code":"KNAPSACK_CAPACITY_LOOP_SORTS"},{"c":"To allow unlimited copies of each item","ok":false,"code":"KNAPSACK_ZERO_ONE_AS_UNBOUNDED"},{"c":"To remove the need for a base case","ok":false,"code":"KNAPSACK_NO_BASE_CASE"}]},
    {"slug":"knapsack-patterns-boundary-v2","skill":"knapsack-patterns","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every distinction that can change a knapsack recurrence.","explanation":"Whether items can repeat and whether the objective counts, maximizes, or tests feasibility changes transitions and iteration order. Input order alone does not define the variant.","options":[{"c":"Whether each item may be chosen more than once","ok":true},{"c":"Whether the objective is maximum value, count, or feasibility","ok":true},{"c":"Whether item descriptions are alphabetically sorted","ok":false,"code":"KNAPSACK_ORDER_DEFINES_VARIANT"},{"c":"Whether the capacity variable is named c or w","ok":false,"code":"KNAPSACK_VARIABLE_NAME_MATTERS"}]},

    {"slug":"linear-search-application-v2","skill":"linear-search","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"A linear search looks for 8 in [3, 8, 8, 10] and must return the first matching index. When should it stop?","explanation":"It should return immediately at index 1, the first position containing 8.","options":[{"c":"At index 1","ok":true},{"c":"At index 2","ok":false,"code":"LINEAR_SEARCH_RETURNS_LAST_DUPLICATE"},{"c":"After scanning the entire array","ok":false,"code":"LINEAR_SEARCH_IGNORES_EARLY_RETURN"},{"c":"Before checking index 0","ok":false,"code":"LINEAR_SEARCH_SKIPS_START"}]},
    {"slug":"linear-search-boundary-v2","skill":"linear-search","type":"MULTI_SELECT","level":"ANALYZE","difficulty":3,"prompt":"Select every situation where linear search is a reasonable direct choice.","explanation":"Linear search works without sorting and is often suitable for small or one-pass data. Repeated searches over static data may justify preprocessing or indexing.","options":[{"c":"A small unsorted collection searched once","ok":true},{"c":"A stream examined until the first matching event","ok":true},{"c":"Millions of repeated lookups in unchanged sortable data","ok":false,"code":"LINEAR_SEARCH_IGNORES_REPEATED_COST"},{"c":"A requirement for guaranteed O(log n) lookup","ok":false,"code":"LINEAR_SEARCH_LOGARITHMIC"}]},

    {"slug":"linked-lists-application-v2","skill":"linked-lists","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"To insert a node after a known singly linked-list node current, which pointer must the new node receive before current.next is replaced?","explanation":"The new node must first point to current's old successor; then current.next can point to the new node without losing the remainder.","options":[{"c":"The old value of current.next","ok":true},{"c":"The list head in every case","ok":false,"code":"LINKED_INSERT_ALWAYS_HEAD"},{"c":"Null in every case","ok":false,"code":"LINKED_INSERT_TRUNCATES_LIST"},{"c":"A pointer to current itself","ok":false,"code":"LINKED_INSERT_SELF_CYCLE"}]},
    {"slug":"linked-lists-boundary-v2","skill":"linked-lists","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every operation that is O(1) in a singly linked list when the relevant node reference is already known.","explanation":"Reading the first node and inserting after a known node are constant time. Finding an index or predecessor requires traversal unless separately stored.","options":[{"c":"Read the head value","ok":true},{"c":"Insert after the known node","ok":true},{"c":"Read the element at an arbitrary index","ok":false,"code":"LINKED_LIST_RANDOM_ACCESS"},{"c":"Find the predecessor of an arbitrary known node","ok":false,"code":"SINGLY_LIST_HAS_BACK_POINTER"}]},

    {"slug":"longest-common-subsequence-application-v2","skill":"longest-common-subsequence","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"For LCS, characters a[i] and b[j] are equal. Which recurrence is used for the state ending at those positions?","explanation":"A matching pair extends an LCS of the preceding prefixes by one.","options":[{"c":"1 plus LCS(i minus 1, j minus 1)","ok":true},{"c":"1 plus LCS(i, j minus 1)","ok":false,"code":"LCS_MATCH_CONSUMES_ONE_STRING"},{"c":"LCS(i minus 1, j) plus LCS(i, j minus 1)","ok":false,"code":"LCS_BRANCHES_SUMMED"},{"c":"Zero regardless of previous prefixes","ok":false,"code":"LCS_MATCH_RESETS"}]},
    {"slug":"longest-common-subsequence-boundary-v2","skill":"longest-common-subsequence","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every true statement about longest common subsequence.","explanation":"A subsequence preserves relative order but need not be contiguous, and reconstruction can follow DP choices. It differs from substring and is not generally the intersection of character sets.","options":[{"c":"Selected characters preserve their order in both sequences","ok":true},{"c":"The characters need not be contiguous","ok":true},{"c":"It is the same as longest common substring","ok":false,"code":"LCS_AS_SUBSTRING"},{"c":"Sorting both strings preserves the original LCS problem","ok":false,"code":"LCS_ORDER_DISCARDED"}]},

    {"slug":"memoization-application-v2","skill":"memoization","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"A recursive function's result depends on position i and remaining budget b. Which cache key is sufficient?","explanation":"Every value that affects future results belongs in the state key; using only i merges different subproblems incorrectly.","options":[{"c":"The pair (i, b)","ok":true},{"c":"Only i","ok":false,"code":"MEMO_INCOMPLETE_KEY"},{"c":"Only the recursion depth","ok":false,"code":"MEMO_DEPTH_AS_STATE"},{"c":"The final answer found so far","ok":false,"code":"MEMO_GLOBAL_ANSWER_AS_KEY"}]},
    {"slug":"memoization-boundary-v2","skill":"memoization","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every condition needed for memoization to return correct reusable results.","explanation":"The cache key must represent the complete state and the function result for that state must be stable. Caching does not require breadth-first order or remove all recursion depth.","options":[{"c":"The cache key captures every input affecting the result","ok":true},{"c":"The same state has the same result within the computation","ok":true},{"c":"States must be evaluated in breadth-first order","ok":false,"code":"MEMO_REQUIRES_BFS"},{"c":"Memoization guarantees constant recursion depth","ok":false,"code":"MEMO_REMOVES_STACK_DEPTH"}]},

    {"slug":"minimum-spanning-trees-application-v2","skill":"minimum-spanning-trees","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"Kruskal's algorithm considers an edge whose endpoints are already connected by selected edges. What should it do?","explanation":"Adding the edge would create a cycle, so Kruskal skips it and considers the next lightest edge.","options":[{"c":"Skip the edge","ok":true},{"c":"Add it because it is currently lightest","ok":false,"code":"MST_IGNORES_CYCLE"},{"c":"Remove every earlier edge","ok":false,"code":"MST_RESTART_ON_CYCLE"},{"c":"Direct the edge from smaller to larger vertex","ok":false,"code":"MST_DIRECTS_EDGE"}]},
    {"slug":"minimum-spanning-trees-boundary-v2","skill":"minimum-spanning-trees","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every true statement about a minimum spanning tree of a connected weighted undirected graph.","explanation":"It connects all vertices without cycles using n minus 1 edges and minimizes total tree weight. It does not necessarily preserve shortest paths or have a unique solution.","options":[{"c":"It contains n minus 1 edges","ok":true},{"c":"It has no cycle","ok":true},{"c":"It preserves shortest paths between every pair","ok":false,"code":"MST_AS_ALL_PAIRS_SHORTEST_PATH"},{"c":"It is unique even when equal-weight alternatives exist","ok":false,"code":"MST_ALWAYS_UNIQUE"}]},

    {"slug":"programming-variables-application-v2","skill":"programming-variables","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"After x = 4, y = x, and x = 9 execute for number values, what value does y hold?","explanation":"The value 4 is assigned to y before x is reassigned, so y remains 4.","options":[{"c":"4","ok":true},{"c":"9","ok":false,"code":"VARIABLE_ASSIGNMENT_AS_LIVE_ALIAS"},{"c":"13","ok":false,"code":"VARIABLE_ASSIGNMENT_AS_ADDITION"},{"c":"Undefined","ok":false,"code":"VARIABLE_REASSIGN_INVALIDATES_COPY"}]},
    {"slug":"programming-variables-boundary-v2","skill":"programming-variables","type":"MULTI_SELECT","level":"ANALYZE","difficulty":3,"prompt":"Select every statement that correctly distinguishes assignment from equality testing.","explanation":"Assignment stores a value in a variable; equality testing produces a Boolean comparison result. Assignment does not prove permanent equality.","options":[{"c":"Assignment can change stored program state","ok":true},{"c":"Equality testing produces a true-or-false result","ok":true},{"c":"After x is assigned y, x and y must remain equal forever","ok":false,"code":"VARIABLE_ASSIGNMENT_PERMANENT_EQUALITY"},{"c":"Equality testing always modifies both operands","ok":false,"code":"COMPARISON_MUTATES_VALUES"}]},

    {"slug":"queues-application-v2","skill":"queues","type":"SINGLE_CHOICE","level":"APPLY","difficulty":2,"prompt":"A queue receives A, then B, then C. One item is removed, then D is added. What is the removal order of the remaining items?","explanation":"A is removed first; the remaining FIFO order is B, C, D.","options":[{"c":"B, C, D","ok":true},{"c":"D, C, B","ok":false,"code":"QUEUE_AS_STACK"},{"c":"A, B, C","ok":false,"code":"QUEUE_REMOVAL_IGNORED"},{"c":"C, B, D","ok":false,"code":"QUEUE_REVERSES_EXISTING_ITEMS"}]},
    {"slug":"queues-boundary-v2","skill":"queues","type":"MULTI_SELECT","level":"ANALYZE","difficulty":3,"prompt":"Select every situation naturally modeled by a FIFO queue.","explanation":"Arrival-order service and BFS frontiers use FIFO. Undo history uses a stack and priority scheduling needs priority ordering.","options":[{"c":"Serving requests in arrival order","ok":true},{"c":"Processing the next BFS frontier","ok":true},{"c":"Undoing the most recent editor action first","ok":false,"code":"QUEUE_AS_STACK"},{"c":"Always processing the highest-priority job first","ok":false,"code":"QUEUE_AS_PRIORITY_QUEUE"}]},

    {"slug":"recursion-application-v2","skill":"recursion","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"A recursive function processes the first item and calls itself on the remaining list. Which base case guarantees termination?","explanation":"When the remaining list is empty, no smaller input exists to process and recursion should return directly.","options":[{"c":"Return when the list is empty","ok":true},{"c":"Return only when the list becomes larger","ok":false,"code":"RECURSION_BASE_MOVES_AWAY"},{"c":"Call itself again on the same list","ok":false,"code":"RECURSION_NO_PROGRESS"},{"c":"Remove the base case and rely on memory limits","ok":false,"code":"RECURSION_STACK_AS_TERMINATION"}]},
    {"slug":"recursion-boundary-v2","skill":"recursion","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every property required for a well-founded recursive algorithm.","explanation":"It needs a terminating base case and recursive calls that move toward it. Multiple calls and global variables are optional, not requirements.","options":[{"c":"At least one reachable base case","ok":true},{"c":"Each recursive path makes progress toward termination","ok":true},{"c":"Every call must make exactly two recursive calls","ok":false,"code":"RECURSION_ALWAYS_BINARY"},{"c":"A global variable must store the answer","ok":false,"code":"RECURSION_REQUIRES_GLOBAL_STATE"}]},

    {"slug":"shortest-paths-application-v2","skill":"shortest-paths","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"Dijkstra's algorithm discovers a shorter route to a vertex already in the priority queue. What should happen?","explanation":"Its distance is relaxed and the queue receives or updates an entry with the improved priority; stale entries can later be ignored.","options":[{"c":"Update the distance and queue priority","ok":true},{"c":"Ignore it because the vertex was seen before","ok":false,"code":"DIJKSTRA_SEEN_AS_FINAL"},{"c":"Make the edge weight zero","ok":false,"code":"DIJKSTRA_MODIFIES_WEIGHT"},{"c":"Restart from the source","ok":false,"code":"DIJKSTRA_RESTART_ON_RELAXATION"}]},
    {"slug":"shortest-paths-boundary-v2","skill":"shortest-paths","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every correct algorithm-and-graph pairing.","explanation":"BFS handles unweighted edges, Dijkstra requires nonnegative weights, and Bellman-Ford can handle negative edges and detect reachable negative cycles.","options":[{"c":"BFS for minimum-edge paths in an unweighted graph","ok":true},{"c":"Dijkstra for graphs with nonnegative edge weights","ok":true},{"c":"Dijkstra for arbitrary negative edge weights","ok":false,"code":"DIJKSTRA_WITH_NEGATIVE_EDGES"},{"c":"BFS for arbitrary weighted shortest paths","ok":false,"code":"BFS_IGNORES_WEIGHTS"}]},

    {"slug":"sliding-window-application-v2","skill":"sliding-window","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"For a fixed-size window sum, the window moves one position right. Which update is correct?","explanation":"Subtract the element leaving on the left and add the new element entering on the right.","options":[{"c":"Subtract the outgoing value and add the incoming value","ok":true},{"c":"Recompute only the incoming value","ok":false,"code":"WINDOW_FORGETS_EXISTING_SUM"},{"c":"Add both outgoing and incoming values","ok":false,"code":"WINDOW_OUTGOING_NOT_REMOVED"},{"c":"Reverse the entire array","ok":false,"code":"WINDOW_REQUIRES_REVERSAL"}]},
    {"slug":"sliding-window-boundary-v2","skill":"sliding-window","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every condition that commonly enables a sliding-window solution.","explanation":"The candidate is contiguous and its state can be updated as boundaries move. With negative values, sum monotonicity may fail for some variable-window techniques.","options":[{"c":"The required segment is contiguous","ok":true},{"c":"Window state can be updated when elements enter or leave","ok":true},{"c":"The technique works unchanged for every non-contiguous subset problem","ok":false,"code":"WINDOW_AS_SUBSET"},{"c":"A positive-sum shrinking rule stays valid with arbitrary negative values","ok":false,"code":"WINDOW_IGNORES_NEGATIVE_VALUES"}]},

    {"slug":"stacks-application-v2","skill":"stacks","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"While checking balanced brackets, a closing bracket is read. What should be compared with it?","explanation":"The most recent unmatched opening bracket is on top of the stack and must be its corresponding type.","options":[{"c":"The opening bracket at the top of the stack","ok":true},{"c":"The oldest opening bracket","ok":false,"code":"STACK_AS_QUEUE"},{"c":"Every earlier character","ok":false,"code":"STACK_FULL_RESCAN"},{"c":"Only the total number of opening brackets","ok":false,"code":"BRACKET_COUNT_IGNORES_ORDER"}]},
    {"slug":"stacks-boundary-v2","skill":"stacks","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every problem naturally supported by a stack.","explanation":"Stacks support nested delimiters and undo in reverse action order. FIFO service and minimum-priority removal need different structures.","options":[{"c":"Matching nested delimiters","ok":true},{"c":"Undoing the most recent action","ok":true},{"c":"Serving requests strictly by arrival time","ok":false,"code":"STACK_AS_QUEUE"},{"c":"Removing the globally smallest item efficiently","ok":false,"code":"STACK_AS_MIN_HEAP"}]},

    {"slug":"strings-application-v2","skill":"strings","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"To test whether a string is a palindrome using two indices, when can the algorithm stop with false?","explanation":"A mismatch between the current left and right characters disproves the palindrome immediately.","options":[{"c":"When the current left and right characters differ","ok":true},{"c":"When the two indices move once","ok":false,"code":"PALINDROME_SINGLE_STEP"},{"c":"Only after sorting the string","ok":false,"code":"PALINDROME_REQUIRES_SORT"},{"c":"Whenever two adjacent characters differ","ok":false,"code":"PALINDROME_ADJACENT_EQUALITY"}]},
    {"slug":"strings-boundary-v2","skill":"strings","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every issue that must be specified before comparing user-entered strings for equality.","explanation":"Case normalization and Unicode normalization can affect intended equality. Memory address and character sorting do not generally define textual equality.","options":[{"c":"Whether comparison is case-sensitive","ok":true},{"c":"Whether equivalent Unicode forms are normalized","ok":true},{"c":"Whether both strings occupy the same memory address","ok":false,"code":"STRING_EQUALITY_AS_IDENTITY"},{"c":"Whether characters should be sorted before every comparison","ok":false,"code":"STRING_EQUALITY_IGNORES_ORDER"}]},

    {"slug":"tabulation-application-v2","skill":"tabulation","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"A DP state dp[i] depends on dp[i minus 1] and dp[i minus 2]. Which fill direction is valid?","explanation":"Smaller indices must be computed before larger indices, so the table is filled from the base states upward.","options":[{"c":"From smaller indices to larger indices","ok":true},{"c":"From larger indices downward without initialized future states","ok":false,"code":"TABULATION_WRONG_ORDER"},{"c":"In random order","ok":false,"code":"TABULATION_IGNORES_DEPENDENCIES"},{"c":"Only compute dp[n] directly","ok":false,"code":"TABULATION_SKIPS_SUBPROBLEMS"}]},
    {"slug":"tabulation-boundary-v2","skill":"tabulation","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every consideration needed when converting memoized recursion to tabulation.","explanation":"Base states must be initialized and evaluation order must satisfy dependencies. A table may sometimes be space-optimized and need not be two-dimensional.","options":[{"c":"Initialize the states corresponding to recursive base cases","ok":true},{"c":"Choose an order in which dependencies are already available","ok":true},{"c":"Always allocate a two-dimensional table","ok":false,"code":"TABULATION_ALWAYS_2D"},{"c":"Preserve recursive call order even when dependencies differ","ok":false,"code":"TABULATION_COPIES_CALL_ORDER"}]},

    {"slug":"topological-sorting-application-v2","skill":"topological-sorting","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"Kahn's algorithm processes fewer vertices than the directed graph contains. What does this establish?","explanation":"A remaining directed cycle prevents every remaining vertex from reaching indegree zero, so no topological ordering exists.","options":[{"c":"The graph contains a directed cycle","ok":true},{"c":"The graph is disconnected and therefore invalid","ok":false,"code":"TOPOLOGICAL_DISCONNECTED_INVALID"},{"c":"The queue implementation was necessarily FIFO-wrong","ok":false,"code":"TOPOLOGICAL_BLAMES_QUEUE"},{"c":"The graph has multiple valid topological orders","ok":false,"code":"TOPOLOGICAL_PARTIAL_AS_MULTIPLE"}]},
    {"slug":"topological-sorting-boundary-v2","skill":"topological-sorting","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every true statement about topological ordering.","explanation":"It exists only for DAGs, respects every directed dependency, and can be non-unique. It is not a shortest-path ordering.","options":[{"c":"Every directed edge u to v places u before v","ok":true},{"c":"A DAG may have more than one valid order","ok":true},{"c":"Every directed graph has such an order","ok":false,"code":"TOPOLOGICAL_ALLOWS_CYCLES"},{"c":"The order always lists vertices by distance from one source","ok":false,"code":"TOPOLOGICAL_AS_BFS_DISTANCE"}]},

    {"slug":"tree-traversal-application-v2","skill":"tree-traversal","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"To evaluate an expression tree where operators are internal nodes, which traversal naturally evaluates children before their operator?","explanation":"Postorder processes left and right subexpressions before applying the operator at their parent.","options":[{"c":"Postorder","ok":true},{"c":"Preorder","ok":false,"code":"EXPRESSION_EVAL_AS_PREFIX_PROCESS"},{"c":"Level order","ok":false,"code":"EXPRESSION_EVAL_BY_DEPTH"},{"c":"Inorder without parentheses","ok":false,"code":"EXPRESSION_INORDER_UNAMBIGUOUS"}]},
    {"slug":"tree-traversal-boundary-v2","skill":"tree-traversal","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every correct traversal use.","explanation":"Preorder can serialize structure with null markers, and level order groups nodes by depth. Inorder is sorted only for BSTs; postorder does not inherently find shortest graph paths.","options":[{"c":"Preorder with null markers can serialize a binary tree","ok":true},{"c":"Level order can process nodes by depth","ok":true},{"c":"Inorder sorts every arbitrary binary tree","ok":false,"code":"INORDER_ALWAYS_SORTED"},{"c":"Postorder guarantees shortest paths in a weighted graph","ok":false,"code":"TREE_TRAVERSAL_AS_SHORTEST_PATH"}]},

    {"slug":"tries-application-v2","skill":"tries","type":"SINGLE_CHOICE","level":"APPLY","difficulty":4,"prompt":"A trie contains the word car, and the path c-a continues to t. What distinguishes car from the prefix ca?","explanation":"A terminal marker on the node for r records that car is a complete stored key; path existence alone represents a prefix.","options":[{"c":"A terminal marker at the r node","ok":true},{"c":"The r node must have no children","ok":false,"code":"TRIE_WORD_MUST_BE_LEAF"},{"c":"The characters are sorted alphabetically","ok":false,"code":"TRIE_WORD_AS_SORTED_CHARS"},{"c":"The path length is greater than two","ok":false,"code":"TRIE_LENGTH_DEFINES_WORD"}]},
    {"slug":"tries-boundary-v2","skill":"tries","type":"MULTI_SELECT","level":"ANALYZE","difficulty":5,"prompt":"Select every true statement about a character trie.","explanation":"Lookup depends mainly on key length and shared prefixes reuse nodes. Memory can be high, and ordinary tries do not rank suggestions by frequency unless augmented.","options":[{"c":"Lookup time is proportional to the key length","ok":true},{"c":"Keys with common prefixes share path nodes","ok":true},{"c":"Memory use is always lower than a hash table","ok":false,"code":"TRIE_ALWAYS_MEMORY_EFFICIENT"},{"c":"Autocomplete frequency ranking is automatic without stored counts","ok":false,"code":"TRIE_AUTOMATIC_RANKING"}]},

    {"slug":"two-pointers-application-v2","skill":"two-pointers","type":"SINGLE_CHOICE","level":"APPLY","difficulty":3,"prompt":"In a sorted ascending array, the sum at left and right is smaller than the target. Which pointer movement can increase the sum?","explanation":"Moving the left pointer right replaces the smaller value with an equal or larger value; moving right left would not increase the sum.","options":[{"c":"Move the left pointer right","ok":true},{"c":"Move the right pointer left","ok":false,"code":"TWO_POINTER_DIRECTION_REVERSED"},{"c":"Move both pointers outside the array","ok":false,"code":"TWO_POINTER_SKIP_SEARCH"},{"c":"Keep both pointers fixed","ok":false,"code":"TWO_POINTER_NO_PROGRESS"}]},
    {"slug":"two-pointers-boundary-v2","skill":"two-pointers","type":"MULTI_SELECT","level":"ANALYZE","difficulty":4,"prompt":"Select every condition supporting the opposite-end two-pointer sum technique.","explanation":"The sequence must be ordered under the comparison and pointer movement must eliminate impossible pairs. Arbitrary unsorted data does not support the same rule directly.","options":[{"c":"Values are sorted under the comparison used","ok":true},{"c":"Each pointer move safely discards impossible pairs","ok":true},{"c":"Values may be in arbitrary order with no preprocessing","ok":false,"code":"TWO_POINTER_IGNORES_ORDER"},{"c":"Both pointers must always move together","ok":false,"code":"TWO_POINTER_ALWAYS_MOVE_BOTH"}]}
  ]
  $bank$::jsonb) AS item(
    slug TEXT, skill TEXT, type TEXT, level TEXT, difficulty SMALLINT,
    prompt TEXT, explanation TEXT, options JSONB
  )
), inserted AS (
  INSERT INTO questions (
    id, skill_id, slug, prompt, question_type, difficulty, explanation,
    status, discrimination, guess_probability, cognitive_level,
    calibration_state, question_purpose, diagnostic_role, construct_code, content_version
  )
  SELECT gen_random_uuid(), skill.id, authored.slug, authored.prompt, authored.type,
         CASE WHEN authored.level = 'ANALYZE' THEN authored.difficulty
              ELSE LEAST(authored.difficulty, 3) END,
         authored.explanation, 'ACTIVE',
         CASE WHEN authored.level = 'ANALYZE' THEN 1.300 ELSE 1.200 END,
         CASE WHEN authored.type = 'MULTI_SELECT' THEN 0.125 ELSE 0.250 END,
         authored.level, 'EXPERT_PRIOR', 'DIAGNOSTIC',
         CASE WHEN authored.level = 'ANALYZE' THEN 'CHALLENGE' ELSE 'VERIFICATION' END,
         CASE WHEN authored.level = 'ANALYZE' THEN 'BOUNDARY' ELSE 'APPLICATION' END,
         2
  FROM authored
  JOIN skills skill ON skill.slug = authored.skill
  ON CONFLICT (slug) DO UPDATE SET
    prompt = EXCLUDED.prompt, question_type = EXCLUDED.question_type,
    difficulty = EXCLUDED.difficulty, explanation = EXCLUDED.explanation,
    status = 'ACTIVE', discrimination = EXCLUDED.discrimination,
    guess_probability = EXCLUDED.guess_probability,
    cognitive_level = EXCLUDED.cognitive_level,
    diagnostic_role = EXCLUDED.diagnostic_role,
    construct_code = EXCLUDED.construct_code,
    content_version = EXCLUDED.content_version,
    updated_at = NOW()
  RETURNING id, slug
)
INSERT INTO question_options (
  id, question_id, option_key, content, is_correct, misconception_code
)
SELECT gen_random_uuid(), inserted.id, chr((64 + option.ordinality)::integer)::char(1),
       option.value->>'c', (option.value->>'ok')::boolean,
       NULLIF(option.value->>'code', '')
FROM authored
JOIN inserted ON inserted.slug = authored.slug
CROSS JOIN LATERAL jsonb_array_elements(authored.options) WITH ORDINALITY AS option(value, ordinality)
ON CONFLICT (question_id, option_key) DO UPDATE SET
  content = EXCLUDED.content,
  is_correct = EXCLUDED.is_correct,
  misconception_code = EXCLUDED.misconception_code;

INSERT INTO question_skill_mappings (question_id, skill_id, mapping_type, evidence_weight)
SELECT id, skill_id, 'PRIMARY', 1.0000
FROM questions
WHERE content_version = 2
  AND diagnostic_role IN ('VERIFICATION', 'CHALLENGE')
ON CONFLICT (question_id, skill_id) DO UPDATE SET
  mapping_type = EXCLUDED.mapping_type,
  evidence_weight = EXCLUDED.evidence_weight;

WITH additions AS (
  SELECT assessment.id AS assessment_id, question.id AS question_id,
         ROW_NUMBER() OVER (
           PARTITION BY assessment.id ORDER BY course_skill.sequence, question.slug
         )::smallint AS offset_sequence
  FROM assessments assessment
  JOIN course_skills course_skill ON course_skill.course_id = assessment.course_id
  JOIN questions question ON question.skill_id = course_skill.skill_id
    AND question.status = 'ACTIVE'
    AND question.question_purpose = 'DIAGNOSTIC'
    AND question.content_version = 2
    AND question.diagnostic_role IN ('VERIFICATION', 'CHALLENGE')
  WHERE assessment.status = 'ACTIVE'
    AND assessment.assessment_type = 'DIAGNOSTIC'
    AND NOT EXISTS (
      SELECT 1 FROM assessment_questions existing
      WHERE existing.assessment_id = assessment.id
        AND existing.question_id = question.id
    )
), maxima AS (
  SELECT assessment.id AS assessment_id,
         COALESCE(MAX(existing.sequence), 0)::smallint AS maximum_sequence
  FROM assessments assessment
  LEFT JOIN assessment_questions existing ON existing.assessment_id = assessment.id
  GROUP BY assessment.id
)
INSERT INTO assessment_questions (assessment_id, question_id, sequence)
SELECT additions.assessment_id, additions.question_id,
       (maxima.maximum_sequence + additions.offset_sequence)::smallint
FROM additions
JOIN maxima ON maxima.assessment_id = additions.assessment_id
ON CONFLICT (assessment_id, question_id) DO NOTHING;

UPDATE system_metadata
SET value = value || '{"phase":25,"status":"curriculum_diagnostic_bank_v2","diagnosticContentVersion":2}'::jsonb,
    updated_at = NOW()
WHERE key = 'application';
