import {
  AlertTriangle, ArrowLeft, BarChart3, BrainCircuit, Check, CircleAlert, Database,
  FlaskConical, GitCompareArrows, LoaderCircle, RefreshCw, ShieldCheck, Sparkles, Workflow,
} from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { ApiError } from "../auth/api";
import { useAuth } from "../auth/AuthContext";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { getGovernanceOverview, type GovernanceOverview } from "../governance/api";

const percent = (value: number | null) => value === null ? "Withheld" : `${Math.round(value * 100)}%`;
const decimal = (value: number | null) => value === null ? "Withheld" : value.toFixed(3);
const pretty = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());

export function GovernancePage() {
  const { accessToken, refreshSession } = useAuth();
  const [overview, setOverview] = useState<GovernanceOverview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const withSession = useCallback(async <T,>(operation: (token: string) => Promise<T>) => {
    if (!accessToken) throw new Error("Your session is not available.");
    try { return await operation(accessToken); }
    catch (requestError) {
      if (requestError instanceof ApiError && requestError.status === 401) return operation(await refreshSession());
      throw requestError;
    }
  }, [accessToken, refreshSession]);
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try { setOverview(await withSession(getGovernanceOverview)); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Model governance could not be loaded."); }
    finally { setLoading(false); }
  }, [withSession]);
  useEffect(() => { void load(); }, [load]);

  if (loading && !overview) return <main className="grid min-h-screen place-items-center bg-[#f4f5f0]"><LoaderCircle className="size-7 animate-spin text-[#356b54]" /></main>;
  if (!overview) return <main className="grid min-h-screen place-items-center bg-[#f4f5f0] p-5"><Card className="max-w-lg"><CardContent className="p-8 text-center"><CircleAlert className="mx-auto size-7 text-[#c06b40]" /><h1 className="mt-3 text-xl font-semibold">Governance unavailable</h1><p className="mt-2 text-sm text-[#6f7c75]">{error}</p><Button className="mt-5" onClick={() => void load()}><RefreshCw className="size-4" /> Retry</Button></CardContent></Card></main>;

  const volume = [["Predictions", overview.volume.predictions], ["Recommendations", overview.volume.recommendations], ["Responses", overview.volume.responses], ["Accepted", overview.volume.accepted], ["Completed", overview.volume.completed], ["Assessed outcomes", overview.volume.assessedOutcomes]];
  const retrainingProgress = Math.min(100, overview.retraining.observedAssessedOutcomes / overview.retraining.requiredAssessedOutcomes * 100);
  const diagnostic = overview.diagnosticQuality;
  const visibleItems = diagnostic.items.filter((item) => item.responseCount > 0 || item.warnings.length > 0).slice(0, 12);
  return <div className="min-h-screen bg-[#f4f5f0] text-[#18372f]"><header className="border-b border-[#dde3da] bg-[#fbfcf8]/95"><div className="mx-auto flex max-w-[1280px] items-center justify-between px-4 py-4 sm:px-7"><Link className="flex items-center gap-3" to="/reviewer"><span className="grid size-10 place-items-center rounded-xl bg-[#163b32] text-white"><Sparkles className="size-5" /></span><div><p className="font-bold">LearnPath</p><p className="text-[11px] text-[#7b8681]">Phase 20 · monitoring & governance</p></div></Link><Button asChild variant="ghost"><Link to="/reviewer"><ArrowLeft className="size-4" /> Reviewer view</Link></Button></div></header>
    <main className="mx-auto max-w-[1280px] px-4 py-8 sm:px-7 sm:py-10"><section className="overflow-hidden rounded-[2rem] bg-[#173d33] p-7 text-white sm:p-10"><Badge className="border-white/10 bg-white/10 text-[#d7e8df]" variant="outline"><ShieldCheck className="mr-1.5 size-3.5" /> Human-controlled model lifecycle</Badge><div className="mt-6 grid gap-7 lg:grid-cols-[1fr_360px] lg:items-end"><div><h1 className="text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Monitor evidence. Withhold weak conclusions.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-[#c5d5ce]">Phase 20 observes the frozen Phase 19 recommender without changing its candidate generation, 55-feature contract, ranking policy, or production model.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f1a271]">Current production model</p><p className="mt-3 text-xl font-semibold">{overview.currentModel?.modelVersion ?? "No deployed path yet"}</p><p className="mt-2 break-all text-xs leading-5 text-[#b9ccc4]">{overview.currentModel?.featureVersion ?? "Waiting for provenance"}</p></div></div></section>
      {overview.rates.state === "INSUFFICIENT_DATA" && <section className="mt-5 flex gap-4 rounded-2xl border border-[#e7b897] bg-[#fff6ed] p-5"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-[#b86138]" /><div><p className="font-semibold">Performance rates are intentionally withheld</p><p className="mt-1 text-sm leading-6 text-[#785f51]">Only {overview.volume.responses} recommendation responses exist. At least {overview.rates.minimumResponses} are required before acceptance, rejection, completion, or assessment-follow-through rates are presented.</p></div></section>}
      <section className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{volume.map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><BarChart3 className="size-4 text-[#3d735a]" /><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-[#6f7c75]">{label}</p></CardContent></Card>)}</section>
      <section className="mt-6 grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><Card><CardContent className="p-6 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ca6e3f]">Sample-gated rates</p><h2 className="mt-2 text-2xl font-semibold">No tiny-sample success claims</h2></div><Database className="size-5 text-[#3d735a]" /></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Acceptance", overview.rates.acceptanceRate], ["Rejection", overview.rates.rejectionRate], ["Completion", overview.rates.completionRate], ["Assessment follow-through", overview.rates.assessmentFollowThrough]].map(([label, value]) => <div className="rounded-2xl bg-[#f4f6f1] p-4" key={String(label)}><p className="text-xl font-semibold">{percent(value as number | null)}</p><p className="mt-1 text-xs text-[#6d7973]">{label}</p></div>)}</div></CardContent></Card><Card><CardContent className="p-6 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ca6e3f]">Prediction distribution</p><h2 className="mt-2 text-2xl font-semibold">Frozen model output</h2><div className="mt-6 grid grid-cols-3 gap-3">{[["P10", overview.predictionDistribution.p10], ["Median", overview.predictionDistribution.median], ["P90", overview.predictionDistribution.p90]].map(([label, value]) => <div className="rounded-2xl bg-[#f4f6f1] p-4 text-center" key={String(label)}><p className="text-xl font-semibold">{percent(value as number | null)}</p><p className="mt-1 text-xs text-[#6d7973]">{label}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-[#718078]">{overview.predictionDistribution.count} persisted candidate predictions · mean {percent(overview.predictionDistribution.mean)}</p></CardContent></Card></section>
      <section className="mt-6 rounded-[1.75rem] border border-[#dce2da] bg-white p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ca6e3f]">Course-level monitoring</p><h2 className="mt-2 text-2xl font-semibold">Volume is visible; conclusions remain gated</h2><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#dfe5dd] text-xs text-[#718078]"><tr><th className="pb-3">Course</th><th className="pb-3">Recommendations</th><th className="pb-3">Responses</th><th className="pb-3">Assessed outcomes</th><th className="pb-3">Acceptance</th><th className="pb-3">Observed gain</th></tr></thead><tbody>{overview.coursePerformance.map((course) => <tr className="border-b border-[#edf0eb]" key={course.courseId}><td className="py-4 font-semibold">{course.courseName}</td><td>{course.recommendations}</td><td>{course.responses}</td><td>{course.assessedOutcomes}</td><td>{percent(course.acceptanceRate)}</td><td>{percent(course.meanObservedGain)}</td></tr>)}</tbody></table></div></section>
      <section className="mt-6 overflow-hidden rounded-[1.75rem] border border-[#d7e1d7] bg-white">
        <div className="border-b border-[#e1e7df] bg-[#173d33] p-6 text-white sm:p-8">
          <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
            <div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#f1a271]">Paper 1 · diagnostic quality lab</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Evidence before accuracy claims</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#c3d5cc]">The adaptive engine is live. Item statistics below come only from persisted submitted diagnostics; empirical discrimination and calibration error stay withheld until each item reaches its sample gate.</p></div>
            <Badge className="self-start border-white/10 bg-white/10 text-[#dce9e3]" variant="outline">{diagnostic.policyVersion}</Badge>
          </div>
        </div>
        <div className="p-6 sm:p-8">
          <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">{[
            ["Learners", diagnostic.cohort.uniqueLearners], ["Attempts", diagnostic.cohort.submittedAttempts],
            ["Responses", diagnostic.cohort.totalResponses], ["Self reports", diagnostic.cohort.selfReportClaims],
            ["Active items", diagnostic.summary.activeItems], ["Observed items", diagnostic.summary.observedItems],
            ["Reportable", diagnostic.summary.reportableItems], ["Mixed evidence", diagnostic.evidence.mixedEvidenceSkills],
          ].map(([label, value]) => <div className="rounded-2xl bg-[#f3f6f0] p-4" key={String(label)}><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-[#718078]">{label}</p></div>)}</div>
          <div className="mt-5 grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
            <Card><CardContent className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#c86b3c]">Session audit</p><h3 className="mt-2 text-xl font-semibold">Why the engine stopped</h3></div><FlaskConical className="size-5 text-[#3c7057]" /></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-[#f5f7f3] p-3"><p className="font-semibold">{diagnostic.cohort.meanQuestions?.toFixed(1) ?? "—"}</p><p className="mt-1 text-[10px] text-[#758179]">Mean questions</p></div><div className="rounded-xl bg-[#f5f7f3] p-3"><p className="font-semibold">{diagnostic.cohort.medianQuestions?.toFixed(0) ?? "—"}</p><p className="mt-1 text-[10px] text-[#758179]">Median</p></div><div className="rounded-xl bg-[#f5f7f3] p-3"><p className="font-semibold">{diagnostic.cohort.p90Questions?.toFixed(0) ?? "—"}</p><p className="mt-1 text-[10px] text-[#758179]">P90</p></div></div><div className="mt-4 space-y-2">{diagnostic.stopReasons.length ? diagnostic.stopReasons.map((reason) => <div className="flex items-center justify-between rounded-xl border border-[#e3e8e0] px-3 py-2 text-xs" key={reason.reason}><span>{pretty(reason.reason)}</span><Badge variant="outline">{reason.count}</Badge></div>) : <p className="rounded-xl border border-dashed border-[#d8e0d5] p-4 text-sm text-[#758179]">No submitted diagnostic sessions yet.</p>}</div></CardContent></Card>
            <Card><CardContent className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#c86b3c]">Decision evidence</p><h3 className="mt-2 text-xl font-semibold">Uncertainty stays visible</h3><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#f5f7f3] p-4"><p className="text-2xl font-semibold">{diagnostic.evidence.skillDecisions}</p><p className="mt-1 text-xs text-[#758179]">Skill decisions</p></div><div className="rounded-xl bg-[#f5f7f3] p-4"><p className="text-2xl font-semibold">{diagnostic.evidence.confidenceIntervalsRecorded}</p><p className="mt-1 text-xs text-[#758179]">Intervals recorded</p></div></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(diagnostic.evidence.classificationCounts).map(([classification, count]) => <Badge key={classification} variant="outline">{pretty(classification)} · {count}</Badge>)}</div><p className="mt-4 text-xs leading-5 text-[#748079]">A mixed result is preserved as contradiction evidence. It triggers confirmation rather than being averaged into false certainty.</p></CardContent></Card>
          </div>
          <div className="mt-5 overflow-x-auto rounded-2xl border border-[#e0e6de]">
            <table className="w-full min-w-[1060px] text-left text-xs"><thead className="bg-[#f4f6f2] text-[#69766f]"><tr><th className="px-4 py-3">Item / skill</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Responses</th><th className="px-4 py-3">Correct</th><th className="px-4 py-3">Empirical difficulty</th><th className="px-4 py-3">Discrimination</th><th className="px-4 py-3">Prior error</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{visibleItems.map((item) => <tr className="border-t border-[#e7ebe5]" key={item.id}><td className="px-4 py-4"><p className="font-semibold">{item.skillName}</p><p className="mt-1 font-mono text-[10px] text-[#829087]">{item.slug}</p></td><td className="px-4 py-4"><p>{pretty(item.diagnosticRole)}</p><p className="mt-1 text-[10px] text-[#829087]">{pretty(item.cognitiveLevel)} · L{item.configuredDifficulty}</p></td><td className="px-4 py-4">{item.responseCount}</td><td className="px-4 py-4">{percent(item.correctRate)}</td><td className="px-4 py-4">{decimal(item.difficultyEstimate)}</td><td className="px-4 py-4">{decimal(item.empiricalDiscrimination)}</td><td className="px-4 py-4">{decimal(item.absoluteCalibrationError)}</td><td className="px-4 py-4"><Badge variant={item.sampleState === "REPORTABLE" ? item.warnings.length ? "warning" : "success" : "outline"}>{pretty(item.sampleState)}</Badge>{item.warnings.length > 0 && <p className="mt-2 max-w-56 text-[10px] leading-4 text-[#9a6846]">{item.warnings.map(pretty).join(" · ")}</p>}</td></tr>)}</tbody></table>
            {!visibleItems.length && <p className="p-6 text-sm text-[#758179]">The item bank is ready; response statistics will appear after submitted diagnostics.</p>}
          </div>
          <p className="mt-4 text-xs leading-5 text-[#718078]">Reportability gate: {diagnostic.minimumResponsesPerItem} responses per item. “Withheld” is deliberate—not missing UI. Author difficulty is an ordinal prior; empirical difficulty is 1 minus observed correct rate.</p>
        </div>
      </section>
      <section className="mt-6 grid gap-4 lg:grid-cols-4">{diagnostic.studyReadiness.map((item) => <Card key={item.key}><CardContent className="p-5"><Badge variant={item.status === "IMPLEMENTED" ? "success" : item.status === "COLLECTING_DATA" ? "warning" : "outline"}>{pretty(item.status)}</Badge><h3 className="mt-4 font-semibold">{item.label}</h3><p className="mt-2 text-xs leading-5 text-[#6f7c75]">{item.detail}</p></CardContent></Card>)}</section>
      <section className="mt-6 grid gap-5 xl:grid-cols-2"><Card><CardContent className="p-6 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ca6e3f]">Calibration</p><h2 className="mt-2 text-2xl font-semibold">Prediction vs. assessed outcome</h2></div><GitCompareArrows className="size-5 text-[#3d735a]" /></div><Badge className="mt-5" variant={overview.calibration.state === "REPORTABLE" ? "success" : "warning"}>{overview.calibration.state === "REPORTABLE" ? "Reportable" : "Insufficient data"}</Badge><p className="mt-4 text-sm leading-6 text-[#68766f]">{overview.calibration.message}</p><p className="mt-4 text-xs text-[#79857f]">{overview.calibration.observedOutcomes}/{overview.calibration.minimumOutcomes} required outcomes</p></CardContent></Card><Card><CardContent className="p-6 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ca6e3f]">Prediction drift</p><h2 className="mt-2 text-2xl font-semibold">Recent vs. reference window</h2></div><Workflow className="size-5 text-[#3d735a]" /></div><Badge className="mt-5" variant={overview.drift.state === "REPORTABLE" ? "success" : "warning"}>{overview.drift.state === "REPORTABLE" ? "Reportable" : "Insufficient data"}</Badge><p className="mt-4 text-sm leading-6 text-[#68766f]">{overview.drift.message}</p><div className="mt-4 flex gap-3 text-xs"><span className="rounded-lg bg-[#f4f6f1] px-3 py-2">Recent {overview.drift.recentPredictions}</span><span className="rounded-lg bg-[#f4f6f1] px-3 py-2">Reference {overview.drift.baselinePredictions}</span></div></CardContent></Card></section>
      <section className="mt-6 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card><CardContent className="p-6 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ca6e3f]">Retraining eligibility</p><h2 className="mt-2 text-2xl font-semibold">Not eligible</h2><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#e8ece6]"><div className="h-full bg-[#dc895c]" style={{ width: `${retrainingProgress}%` }} /></div><p className="mt-3 text-sm">{overview.retraining.observedAssessedOutcomes}/{overview.retraining.requiredAssessedOutcomes} assessed outcomes</p><div className="mt-5 space-y-2">{overview.retraining.reasons.map((reason) => <p className="flex gap-2 text-xs leading-5 text-[#6e7a74]" key={reason}><CircleAlert className="mt-0.5 size-3.5 shrink-0 text-[#c06b40]" />{reason}</p>)}</div><div className="mt-5 flex flex-wrap gap-2"><Badge variant={overview.retraining.contentCoveragePass ? "success" : "warning"}>Content coverage {overview.retraining.contentCoveragePass ? "passes" : "fails"}</Badge><Badge variant={overview.retraining.dataQualityPass ? "success" : "warning"}>Data quality {overview.retraining.dataQualityPass ? "passes" : "fails"}</Badge></div></CardContent></Card><Card><CardContent className="p-6 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ca6e3f]">Human-controlled promotion</p><h2 className="mt-2 text-2xl font-semibold">No model replaces production automatically</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{overview.promotion.stages.map((stage, index) => <div className="flex items-center gap-3 rounded-2xl border border-[#dfe5dd] p-4" key={stage}><span className={`grid size-8 shrink-0 place-items-center rounded-full text-xs font-bold ${index === 0 ? "bg-[#2f7156] text-white" : "bg-[#edf1ea] text-[#65746d]"}`}>{index === 0 ? <Check className="size-4" /> : index + 1}</span><p className="text-sm font-semibold">{stage}</p></div>)}</div><p className="mt-5 flex gap-2 text-xs leading-5 text-[#6e7a74]"><BrainCircuit className="mt-0.5 size-4 shrink-0 text-[#3d735a]" />Every candidate model must preserve offline evaluation, comparison evidence, explicit approval, and model-version history.</p></CardContent></Card></section>
    </main></div>;
}
